import { Exercise } from './types';

export const exercises: Exercise[] = [
  // CHEST - GYM
  { id: 'bench-press', name: 'Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Bench', level: 'intermediate', type: 'gym', description: 'The king of chest exercises. Builds mass and strength in the pectorals.', instructions: ['Lie flat on bench with feet on floor', 'Grip barbell slightly wider than shoulders', 'Lower bar to mid-chest with control', 'Press up explosively to lockout'], commonMistakes: ['Bouncing bar off chest', 'Flaring elbows too wide', 'Lifting hips off bench'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Bench Press in a modern gym, showing full body movement, perfect posture, muscle engagement, multiple camera angles, loopable, professional fitness tutorial style.', videoUrl: '/videos/bench-press.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'incline-db-press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbells, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets the upper chest for a complete pectoral development.', instructions: ['Set bench to 30-45 degrees', 'Press dumbbells up from shoulder level', 'Squeeze at the top', 'Lower with control'], commonMistakes: ['Bench angle too steep', 'Not full range of motion', 'Using momentum'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Incline Dumbbell Press in a modern gym.', videoUrl: '/videos/incline-db-press.mp4', sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'cable-fly', name: 'Cable Fly', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Isolation exercise for chest with constant tension throughout the movement.', instructions: ['Stand between cable stations', 'Slight bend in elbows', 'Bring handles together in arc motion', 'Squeeze chest at center'], commonMistakes: ['Too much elbow bend', 'Using too much weight', 'Leaning too far forward'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Cable Fly in a modern gym.', videoUrl: '/videos/cable-fly.mp4', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'dips-chest', name: 'Chest Dips', muscleGroup: 'Chest', equipment: 'Dip Station', level: 'intermediate', type: 'gym', description: 'Compound movement targeting lower chest with bodyweight.', instructions: ['Lean forward slightly on dip bars', 'Lower body until upper arms are parallel', 'Push up explosively', 'Keep elbows slightly flared'], commonMistakes: ['Going too deep', 'Not leaning forward enough', 'Swinging body'], musclesWorked: ['Lower Pectoralis', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Chest Dips in a modern gym.', videoUrl: '/videos/dips-chest.mp4', sets: 3, reps: '10-15', restSeconds: 75 },

  // BACK - GYM
  { id: 'deadlift', name: 'Deadlift', muscleGroup: 'Back', equipment: 'Barbell', level: 'advanced', type: 'gym', description: 'The ultimate compound lift for total posterior chain development.', instructions: ['Stand with feet hip-width apart', 'Grip bar just outside knees', 'Drive through heels, keep bar close', 'Lock out hips at top'], commonMistakes: ['Rounding lower back', 'Bar drifting forward', 'Jerking the weight up'], musclesWorked: ['Erector Spinae', 'Glutes', 'Hamstrings', 'Traps', 'Lats'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Deadlift in a modern gym.', videoUrl: '/videos/deadlift.mp4', sets: 4, reps: '5-8', restSeconds: 120 },
  { id: 'barbell-row', name: 'Barbell Row', muscleGroup: 'Back', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Builds thick back muscles and improves posture.', instructions: ['Hinge at hips, slight knee bend', 'Pull bar to lower chest', 'Squeeze shoulder blades together', 'Lower with control'], commonMistakes: ['Standing too upright', 'Using momentum', 'Not squeezing at top'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids', 'Biceps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Barbell Row in a modern gym.', videoUrl: '/videos/barbell-row.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroup: 'Back', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Excellent for building wide lats and V-taper.', instructions: ['Grip bar wider than shoulders', 'Pull down to upper chest', 'Lean back slightly', 'Control the return'], commonMistakes: ['Pulling behind neck', 'Using too much body momentum', 'Grip too narrow'], musclesWorked: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoids'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Lat Pulldown in a modern gym.', videoUrl: '/videos/lat-pulldown.mp4', sets: 4, reps: '10-12', restSeconds: 75 },

  // SHOULDERS - GYM
  { id: 'overhead-press', name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'The premier shoulder mass builder. Builds boulder shoulders.', instructions: ['Start with bar at collar bone', 'Press overhead to lockout', 'Keep core tight throughout', 'Lower with control to starting position'], commonMistakes: ['Excessive back arch', 'Not locking out', 'Pressing in front of face'], musclesWorked: ['Anterior Deltoids', 'Lateral Deltoids', 'Triceps', 'Upper Chest'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Overhead Press in a modern gym.', videoUrl: '/videos/overhead-press.mp4', sets: 4, reps: '8-10', restSeconds: 90 },
  { id: 'lateral-raise', name: 'Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Isolation exercise for building wide, capped deltoids.', instructions: ['Hold dumbbells at sides', 'Raise arms to shoulder height', 'Lead with elbows', 'Lower slowly'], commonMistakes: ['Using too much weight', 'Swinging body', 'Raising above shoulder level'], musclesWorked: ['Lateral Deltoids'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Lateral Raise in a modern gym.', videoUrl: '/videos/lateral-raise.mp4', sets: 4, reps: '12-15', restSeconds: 60 },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'Shoulders', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Essential for rear delts and shoulder health.', instructions: ['Set cable at face height', 'Pull rope to face level', 'Externally rotate at end', 'Squeeze rear delts'], commonMistakes: ['Cable set too low', 'Not externally rotating', 'Using too much weight'], musclesWorked: ['Rear Deltoids', 'Rotator Cuff', 'Upper Traps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Face Pull in a modern gym.', videoUrl: '/videos/face-pull.mp4', sets: 3, reps: '15-20', restSeconds: 45 },

  // ARMS - GYM
  { id: 'barbell-curl', name: 'Barbell Curl', muscleGroup: 'Arms', equipment: 'Barbell', level: 'beginner', type: 'gym', description: 'Classic bicep builder for peak and mass.', instructions: ['Stand with shoulder-width grip', 'Curl bar up keeping elbows pinned', 'Squeeze biceps at top', 'Lower with control'], commonMistakes: ['Swinging body', 'Moving elbows forward', 'Not full ROM'], musclesWorked: ['Biceps Brachii', 'Brachialis'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Barbell Curl in a modern gym.', videoUrl: '/videos/barbell-curl.mp4', sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'skull-crusher', name: 'Skull Crusher', muscleGroup: 'Arms', equipment: 'EZ Bar, Bench', level: 'intermediate', type: 'gym', description: 'Targets all three heads of the triceps for maximum arm size.', instructions: ['Lie on bench holding EZ bar', 'Lower bar toward forehead', 'Keep upper arms vertical', 'Extend arms to lockout'], commonMistakes: ['Elbows flaring out', 'Moving upper arms', 'Going too heavy'], musclesWorked: ['Triceps (all heads)'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Skull Crusher in a modern gym.', videoUrl: '/videos/skull-crusher.mp4', sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroup: 'Arms', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Builds brachialis and forearms for thicker arms.', instructions: ['Hold dumbbells with neutral grip', 'Curl up keeping palms facing each other', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Swinging body', 'Rotating wrists', 'Going too fast'], musclesWorked: ['Brachialis', 'Brachioradialis', 'Biceps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Hammer Curl in a modern gym.', videoUrl: '/videos/hammer-curl.mp4', sets: 3, reps: '10-12', restSeconds: 60 },

  // LEGS - GYM
  { id: 'barbell-squat', name: 'Barbell Squat', muscleGroup: 'Legs', equipment: 'Barbell, Squat Rack', level: 'intermediate', type: 'gym', description: 'The king of all exercises. Builds massive legs and overall strength.', instructions: ['Bar on upper traps', 'Feet shoulder-width apart', 'Squat to parallel or below', 'Drive through heels to stand'], commonMistakes: ['Knees caving in', 'Not hitting depth', 'Leaning too far forward', 'Heels lifting'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Barbell Squat in a modern gym.', videoUrl: '/videos/barbell-squat.mp4', sets: 4, reps: '6-10', restSeconds: 120 },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'Legs', equipment: 'Leg Press Machine', level: 'beginner', type: 'gym', description: 'Machine-based quad builder with less spinal load.', instructions: ['Sit with back flat against pad', 'Place feet shoulder-width on platform', 'Lower until 90 degree knee angle', 'Press up without locking knees'], commonMistakes: ['Letting hips lift off pad', 'Locking out knees', 'Too narrow foot placement'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Leg Press in a modern gym.', videoUrl: '/videos/leg-press.mp4', sets: 4, reps: '10-12', restSeconds: 90 },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroup: 'Legs', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Best exercise for hamstring and glute development.', instructions: ['Hold bar at hip level', 'Hinge at hips pushing them back', 'Keep slight knee bend', 'Feel stretch in hamstrings, reverse'], commonMistakes: ['Rounding back', 'Bending knees too much', 'Not hinging enough'], musclesWorked: ['Hamstrings', 'Glutes', 'Erector Spinae'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Romanian Deadlift in a modern gym.', videoUrl: '/videos/romanian-deadlift.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'leg-curl', name: 'Leg Curl', muscleGroup: 'Legs', equipment: 'Leg Curl Machine', level: 'beginner', type: 'gym', description: 'Isolates hamstrings for balanced leg development.', instructions: ['Lie face down on machine', 'Curl weight toward glutes', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Lifting hips off pad', 'Using momentum', 'Not full ROM'], musclesWorked: ['Hamstrings'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Leg Curl in a modern gym.', videoUrl: '/videos/leg-curl.mp4', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'calf-raise', name: 'Standing Calf Raise', muscleGroup: 'Legs', equipment: 'Calf Raise Machine', level: 'beginner', type: 'gym', description: 'Builds defined calves with full range of motion.', instructions: ['Stand on platform with balls of feet', 'Rise up onto toes', 'Pause at top', 'Lower below platform level'], commonMistakes: ['Bouncing reps', 'Not enough ROM', 'Going too fast'], musclesWorked: ['Gastrocnemius', 'Soleus'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Standing Calf Raise in a modern gym.', videoUrl: '/videos/calf-raise.mp4', sets: 4, reps: '15-20', restSeconds: 45 },

  // ABS - GYM
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'Abs', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Weighted ab exercise for building thick, defined abs.', instructions: ['Kneel in front of cable machine', 'Hold rope behind head', 'Crunch down bringing elbows to knees', 'Control the return'], commonMistakes: ['Hip flexion instead of spinal flexion', 'Using too much weight', 'Not controlling negative'], musclesWorked: ['Rectus Abdominis'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Cable Crunch in a modern gym.', videoUrl: '/videos/cable-crunch.mp4', sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'Abs', equipment: 'Pull-up Bar', level: 'intermediate', type: 'gym', description: 'Advanced lower ab exercise that builds core control.', instructions: ['Hang from pull-up bar', 'Raise legs to parallel or higher', 'Control the lowering phase', 'Avoid swinging'], commonMistakes: ['Using momentum', 'Not raising high enough', 'Swinging'], musclesWorked: ['Lower Abs', 'Hip Flexors'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Hanging Leg Raise in a modern gym.', videoUrl: '/videos/hanging-leg-raise.mp4', sets: 3, reps: '10-15', restSeconds: 60 },

  // GLUTES - GYM
  { id: 'hip-thrust', name: 'Hip Thrust', muscleGroup: 'Glutes', equipment: 'Barbell, Bench', level: 'intermediate', type: 'gym', description: 'The #1 glute builder. Maximum glute activation.', instructions: ['Upper back on bench', 'Bar across hips with pad', 'Drive hips up to full extension', 'Squeeze glutes at top'], commonMistakes: ['Hyperextending lower back', 'Not full hip extension', 'Feet too far forward'], musclesWorked: ['Gluteus Maximus', 'Hamstrings'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Hip Thrust in a modern gym.', videoUrl: '/videos/hip-thrust.mp4', sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroup: 'Glutes', equipment: 'Dumbbells, Bench', level: 'intermediate', type: 'gym', description: 'Unilateral exercise that builds glutes and fixes imbalances.', instructions: ['Rear foot on bench', 'Lower until front thigh is parallel', 'Drive through front heel', 'Keep torso upright'], commonMistakes: ['Front knee going past toe', 'Leaning too far forward', 'Back foot too far from bench'], musclesWorked: ['Glutes', 'Quadriceps', 'Hamstrings'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Bulgarian Split Squat in a modern gym.', videoUrl: '/videos/bulgarian-split-squat.mp4', sets: 3, reps: '10-12 each', restSeconds: 75 },

  // CALISTHENICS
  { id: 'push-up', name: 'Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Fundamental bodyweight chest exercise. Master this before moving to advanced variations.', instructions: ['Hands shoulder-width apart', 'Body in straight line from head to heels', 'Lower chest to floor', 'Push up to full extension'], commonMistakes: ['Hips sagging', 'Elbows flaring 90 degrees', 'Not full ROM'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Push-Up in an outdoor park or minimalist gym, full body visible, controlled movement, perfect technique, loopable video.', sets: 4, reps: '15-25', restSeconds: 60 },
  { id: 'pull-up', name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'intermediate', type: 'calisthenics', description: 'The ultimate back builder using bodyweight. Builds a wide V-taper.', instructions: ['Grip bar slightly wider than shoulders', 'Pull until chin clears bar', 'Lower with full control', 'Start from dead hang'], commonMistakes: ['Kipping or swinging', 'Not going to full hang', 'Chin not clearing bar'], musclesWorked: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoids', 'Core'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Pull-Up in an outdoor park.', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'dips-calisthenics', name: 'Dips', muscleGroup: 'Chest', equipment: 'Parallel Bars', level: 'intermediate', type: 'calisthenics', description: 'Upper body mass builder targeting chest and triceps.', instructions: ['Grip parallel bars', 'Lower body with control', 'Push up to lockout', 'Lean forward for chest focus'], commonMistakes: ['Going too deep', 'Not locking out', 'Swinging'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Dips in an outdoor park.', sets: 3, reps: '10-15', restSeconds: 75 },
  { id: 'handstand-push-up', name: 'Handstand Push-Up', muscleGroup: 'Shoulders', equipment: 'Wall', level: 'advanced', type: 'calisthenics', description: 'Advanced shoulder exercise requiring strength and balance.', instructions: ['Kick up to handstand against wall', 'Lower head toward floor', 'Press back up to full extension', 'Keep core tight'], commonMistakes: ['Not going deep enough', 'Arching back', 'Kicking up unsafely'], musclesWorked: ['Deltoids', 'Triceps', 'Upper Chest', 'Core'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Handstand Push-Up against a wall.', sets: 3, reps: '5-8', restSeconds: 120 },
  { id: 'muscle-up', name: 'Muscle-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'advanced', type: 'calisthenics', description: 'The pinnacle of upper body calisthenics. Combines pull-up and dip.', instructions: ['Start from dead hang', 'Explosive pull above the bar', 'Transition to dip position', 'Press to lockout above bar'], commonMistakes: ['Not enough explosive pull', 'Chicken winging', 'Kipping too much'], musclesWorked: ['Lats', 'Chest', 'Triceps', 'Biceps', 'Core'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Muscle-Up on an outdoor bar.', sets: 3, reps: '3-5', restSeconds: 120 },
  { id: 'l-sit', name: 'L-Sit', muscleGroup: 'Abs', equipment: 'Parallel Bars or Floor', level: 'advanced', type: 'calisthenics', description: 'Isometric core exercise that builds incredible ab strength.', instructions: ['Support body on hands', 'Extend legs straight in front', 'Hold position with legs parallel to floor', 'Keep shoulders depressed'], commonMistakes: ['Bending knees', 'Shoulders rising', 'Not holding long enough'], musclesWorked: ['Abs', 'Hip Flexors', 'Triceps', 'Shoulders'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing L-Sit hold.', sets: 3, reps: '15-30s hold', restSeconds: 90 },
  { id: 'pistol-squat', name: 'Pistol Squat', muscleGroup: 'Legs', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Single-leg squat requiring extreme strength and balance.', instructions: ['Stand on one leg', 'Extend other leg forward', 'Squat down to full depth', 'Stand back up without assistance'], commonMistakes: ['Heel lifting', 'Losing balance', 'Not going deep enough'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Pistol Squat in a park.', sets: 3, reps: '5-8 each', restSeconds: 90 },
  { id: 'dragon-flag', name: 'Dragon Flag', muscleGroup: 'Abs', equipment: 'Bench', level: 'advanced', type: 'calisthenics', description: 'Bruce Lee\'s signature ab exercise. Builds steel-like core.', instructions: ['Lie on bench, grip behind head', 'Raise entire body to vertical', 'Lower body keeping rigid', 'Only shoulder blades touch bench'], commonMistakes: ['Bending at hips', 'Going too fast', 'Not enough control'], musclesWorked: ['Entire Core', 'Hip Flexors', 'Lower Back'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Dragon Flag on a bench.', sets: 3, reps: '5-8', restSeconds: 90 },
  { id: 'planche-lean', name: 'Planche Lean', muscleGroup: 'Shoulders', equipment: 'Floor', level: 'advanced', type: 'calisthenics', description: 'Builds the shoulder and wrist strength needed for planche.', instructions: ['Start in push-up position', 'Lean forward shifting weight to hands', 'Keep arms straight', 'Hold the lean position'], commonMistakes: ['Bending arms', 'Not leaning far enough', 'Hips too high'], musclesWorked: ['Anterior Deltoids', 'Core', 'Wrist Flexors'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Planche Lean.', sets: 3, reps: '15-20s hold', restSeconds: 60 },
  { id: 'australian-pull-up', name: 'Australian Pull-Up', muscleGroup: 'Back', equipment: 'Low Bar', level: 'beginner', type: 'calisthenics', description: 'Horizontal pulling movement. Great progression toward full pull-ups.', instructions: ['Hang under a low bar', 'Pull chest to bar', 'Keep body in straight line', 'Lower with control'], commonMistakes: ['Hips sagging', 'Not pulling to chest', 'Using momentum'], musclesWorked: ['Lats', 'Rhomboids', 'Biceps', 'Rear Deltoids'], videoPrompt: 'Create a 10-20 second HD calisthenics tutorial showing Australian Pull-Up in an outdoor park.', sets: 3, reps: '12-15', restSeconds: 60 },
];

export const getExercisesByMuscleGroup = (group: string) => exercises.filter(e => e.muscleGroup === group);
export const getExercisesByType = (type: 'gym' | 'calisthenics') => exercises.filter(e => e.type === type);
export const getExerciseById = (id: string) => exercises.find(e => e.id === id);
