import { Exercise } from './types';

export const exercises: Exercise[] = [
  // ===== CHEST - GYM (14 exercises) =====
  { id: 'bench-press', name: 'Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Bench', level: 'beginner', type: 'gym', description: 'The king of chest exercises. Builds mass and strength in the pectorals.', instructions: ['Lie flat on bench with feet on floor', 'Grip barbell slightly wider than shoulders', 'Lower bar to mid-chest with control', 'Press up explosively to lockout'], commonMistakes: ['Bouncing bar off chest', 'Flaring elbows too wide', 'Lifting hips off bench'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Bench Press in a modern gym.', videoUrl: '/videos/bench-press.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'incline-bench', name: 'Incline Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets the upper chest for complete development.', instructions: ['Set bench to 30-45 degrees', 'Grip barbell slightly wider than shoulders', 'Lower bar to upper chest', 'Press up to lockout'], commonMistakes: ['Bench angle too steep', 'Bouncing off chest', 'Flaring elbows'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'], videoPrompt: 'Create a high-quality 10-20 second HD fitness tutorial video demonstrating Incline Bench Press in a modern gym.', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'decline-bench', name: 'Decline Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Decline Bench', level: 'intermediate', type: 'gym', description: 'Emphasizes the lower chest fibers.', instructions: ['Secure feet on decline bench', 'Grip barbell slightly wider than shoulders', 'Lower bar to lower chest', 'Press up to lockout'], commonMistakes: ['Not securing feet', 'Too much decline', 'Bouncing bar'], musclesWorked: ['Lower Pectoralis', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Decline Bench Press in a modern gym.', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'flat-db-fly', name: 'Flat Dumbbell Fly', muscleGroup: 'Chest', equipment: 'Dumbbells, Bench', level: 'beginner', type: 'gym', description: 'Isolation movement stretching the chest fibers for width.', instructions: ['Lie flat with dumbbells above chest', 'Open arms wide in arc motion', 'Feel stretch in chest', 'Squeeze back to top'], commonMistakes: ['Going too deep', 'Bending elbows too much', 'Using momentum'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], videoPrompt: 'Flat Dumbbell Fly in a modern gym.', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'incline-db-fly', name: 'Incline Dumbbell Fly', muscleGroup: 'Chest', equipment: 'Dumbbells, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets upper chest with isolation.', instructions: ['Set bench to 30-45 degrees', 'Open arms wide in arc motion', 'Feel stretch in upper chest', 'Squeeze back to top'], commonMistakes: ['Bench too steep', 'Not enough ROM', 'Too heavy'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids'], videoPrompt: 'Incline Dumbbell Fly in a modern gym.', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'peck-deck', name: 'Peck Deck', muscleGroup: 'Chest', equipment: 'Machine', level: 'beginner', type: 'gym', description: 'Machine chest isolation with constant tension.', instructions: ['Sit with back against pad', 'Grip handles at chest level', 'Bring handles together', 'Squeeze chest at center'], commonMistakes: ['Too much weight', 'Not full ROM', 'Shrugging shoulders'], musclesWorked: ['Pectoralis Major'], videoPrompt: 'Peck Deck in a modern gym.', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'incline-db-press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbells, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets the upper chest for a complete pectoral development.', instructions: ['Set bench to 30-45 degrees', 'Press dumbbells up from shoulder level', 'Squeeze at the top', 'Lower with control'], commonMistakes: ['Bench angle too steep', 'Not full range of motion', 'Using momentum'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'], videoPrompt: 'Incline Dumbbell Press in a modern gym.', videoUrl: '/videos/incline-db-press.mp4', sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'cable-fly', name: 'Cable Fly', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Isolation exercise for chest with constant tension.', instructions: ['Stand between cable stations', 'Slight bend in elbows', 'Bring handles together in arc motion', 'Squeeze chest at center'], commonMistakes: ['Too much elbow bend', 'Using too much weight', 'Leaning too far forward'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], videoPrompt: 'Cable Fly in a modern gym.', videoUrl: '/videos/cable-fly.mp4', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'cable-crossover', name: 'Cable Crossover', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'intermediate', type: 'gym', description: 'Full range chest isolation with constant cable tension.', instructions: ['Set cables at high position', 'Step forward, slight lean', 'Bring hands together in low arc', 'Squeeze chest at bottom'], commonMistakes: ['Too much weight', 'Not enough lean', 'Rushing reps'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], videoPrompt: 'Cable Crossover in a modern gym.', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'dips-chest', name: 'Chest Dips', muscleGroup: 'Chest', equipment: 'Dip Station', level: 'intermediate', type: 'gym', description: 'Compound movement targeting lower chest.', instructions: ['Lean forward on dip bars', 'Lower body until upper arms parallel', 'Push up explosively', 'Keep elbows slightly flared'], commonMistakes: ['Going too deep', 'Not leaning forward', 'Swinging body'], musclesWorked: ['Lower Pectoralis', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Chest Dips in a modern gym.', videoUrl: '/videos/dips-chest.mp4', sets: 3, reps: '10-15', restSeconds: 75 },
  { id: 'press-machine', name: 'Chest Press Machine', muscleGroup: 'Chest', equipment: 'Machine', level: 'beginner', type: 'gym', description: 'Machine-based pressing for controlled chest training.', instructions: ['Sit with back flat', 'Grip handles at chest level', 'Press forward to extension', 'Return with control'], commonMistakes: ['Seat too high/low', 'Not full ROM', 'Locking out aggressively'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Chest Press Machine in a modern gym.', sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'db-press-flat', name: 'Flat Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbells, Bench', level: 'intermediate', type: 'gym', description: 'Allows greater ROM than barbell for chest development.', instructions: ['Lie flat with dumbbells at chest', 'Press up to lockout', 'Lower with control', 'Squeeze at top'], commonMistakes: ['Dumbbells too wide', 'Not enough control', 'Arching excessively'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Flat Dumbbell Press in a modern gym.', sets: 4, reps: '8-12', restSeconds: 75 },
  { id: 'smith-bench', name: 'Smith Machine Bench Press', muscleGroup: 'Chest', equipment: 'Smith Machine', level: 'intermediate', type: 'gym', description: 'Guided bench press for controlled chest training.', instructions: ['Lie under Smith machine bar', 'Grip slightly wider than shoulders', 'Unrack and lower to chest', 'Press up to lockout'], commonMistakes: ['Bar path too forward/back', 'Not enough ROM', 'Relying on the machine'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Smith Machine Bench Press.', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'close-grip-bench', name: 'Close-Grip Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Bench', level: 'intermediate', type: 'gym', description: 'Targets inner chest and triceps with narrow grip.', instructions: ['Grip barbell shoulder-width or narrower', 'Lower to lower chest', 'Press up keeping elbows close', 'Lockout at top'], commonMistakes: ['Grip too narrow', 'Flaring elbows', 'Bouncing off chest'], musclesWorked: ['Inner Pectoralis', 'Triceps'], videoPrompt: 'Close-Grip Bench Press.', sets: 4, reps: '8-12', restSeconds: 75 },

  // ===== CHEST - CALISTHENICS (16 exercises) =====
  { id: 'push-up', name: 'Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Fundamental bodyweight chest exercise.', instructions: ['Hands shoulder-width apart', 'Body in straight line', 'Lower chest to floor', 'Push up to full extension'], commonMistakes: ['Hips sagging', 'Elbows flaring 90°', 'Not full ROM'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], videoPrompt: 'Push-Up calisthenics tutorial.', videoUrl: '/videos/push-up.mp4', sets: 4, reps: '15-25', restSeconds: 60 },
  { id: 'diamond-push-up', name: 'Diamond Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Narrow hand placement targeting inner chest and triceps.', instructions: ['Form diamond shape with hands', 'Lower chest to hands', 'Push up to full extension', 'Keep elbows close to body'], commonMistakes: ['Hands too far forward', 'Flaring elbows', 'Hips sagging'], musclesWorked: ['Inner Pectoralis', 'Triceps', 'Core'], videoPrompt: 'Diamond Push-Up calisthenics tutorial.', sets: 3, reps: '10-15', restSeconds: 60 },
  { id: 'decline-push-up', name: 'Decline Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Feet elevated to target upper chest.', instructions: ['Place feet on elevated surface', 'Hands shoulder-width on floor', 'Lower chest to floor', 'Push up with control'], commonMistakes: ['Too much elevation', 'Hips sagging', 'Not full ROM'], musclesWorked: ['Upper Pectoralis', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Decline Push-Up tutorial.', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'archer-push-up', name: 'Archer Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Unilateral push-up variation for advanced chest training.', instructions: ['Wide hand placement', 'Shift weight to one arm', 'Lower to working arm side', 'Push back up and alternate'], commonMistakes: ['Not enough weight shift', 'Rushing reps', 'Collapsing core'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], videoPrompt: 'Archer Push-Up tutorial.', sets: 3, reps: '6-8 each', restSeconds: 90 },
  { id: 'explosive-push-up', name: 'Explosive Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Plyometric push-up for power and fast-twitch fiber activation.', instructions: ['Start in push-up position', 'Lower with control', 'Explode up lifting hands off floor', 'Land softly and repeat'], commonMistakes: ['Not enough explosion', 'Poor landing mechanics', 'Hips dropping'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], videoPrompt: 'Explosive Push-Up tutorial.', sets: 3, reps: '8-12', restSeconds: 90 },
  { id: 'hindu-push-up', name: 'Hindu Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Flowing movement working chest, shoulders, and flexibility.', instructions: ['Start in downward dog', 'Swoop down and forward', 'Push through to cobra position', 'Return to downward dog'], commonMistakes: ['Not enough swoop', 'Rushing movement', 'Not using full ROM'], musclesWorked: ['Pectoralis Major', 'Deltoids', 'Triceps', 'Core'], videoPrompt: 'Hindu Push-Up tutorial.', sets: 3, reps: '10-15', restSeconds: 60 },
  { id: 'pseudo-planche-push-up', name: 'Pseudo Planche Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Hands turned back, leaning forward for extreme chest and shoulder work.', instructions: ['Place hands by hips, fingers pointing back', 'Lean forward significantly', 'Lower chest to floor', 'Push up maintaining lean'], commonMistakes: ['Not enough lean', 'Fingers pointing forward', 'Losing core tension'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids', 'Core'], videoPrompt: 'Pseudo Planche Push-Up tutorial.', sets: 3, reps: '6-10', restSeconds: 90 },
  { id: 'pause-push-up', name: 'Pause Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Pausing at the bottom eliminates momentum for maximum tension.', instructions: ['Lower to bottom position', 'Pause for 2-3 seconds', 'Push up explosively', 'Maintain body alignment'], commonMistakes: ['Not pausing long enough', 'Losing tension at bottom', 'Hips sagging'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], videoPrompt: 'Pause Push-Up tutorial.', sets: 3, reps: '8-12', restSeconds: 60 },
  { id: 'weighted-push-up', name: 'Weighted Push-Up', muscleGroup: 'Chest', equipment: 'Weight Plate', level: 'advanced', type: 'calisthenics', description: 'Added resistance for progressive overload on push-ups.', instructions: ['Place weight plate on upper back', 'Perform standard push-up', 'Maintain alignment with weight', 'Control the descent'], commonMistakes: ['Weight sliding', 'Losing form', 'Too much weight'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], videoPrompt: 'Weighted Push-Up tutorial.', sets: 4, reps: '8-12', restSeconds: 75 },
  { id: 'ring-push-up', name: 'Ring Push-Up', muscleGroup: 'Chest', equipment: 'Gymnastic Rings', level: 'advanced', type: 'calisthenics', description: 'Unstable surface forces greater stabilizer activation.', instructions: ['Set rings at low height', 'Grip rings in push-up position', 'Lower with control', 'Push up and turn rings out at top'], commonMistakes: ['Rings too high', 'Not stabilizing', 'Rushing reps'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core', 'Stabilizers'], videoPrompt: 'Ring Push-Up tutorial.', sets: 3, reps: '8-12', restSeconds: 75 },
  { id: 'one-arm-push-up', name: 'One-Arm Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Ultimate unilateral chest and core challenge.', instructions: ['Wide stance for balance', 'One hand on floor, other behind back', 'Lower with control', 'Push up maintaining alignment'], commonMistakes: ['Rotating hips', 'Not enough depth', 'Stance too narrow'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core', 'Obliques'], videoPrompt: 'One-Arm Push-Up tutorial.', sets: 3, reps: '3-5 each', restSeconds: 120 },
  { id: 'incline-push-up', name: 'Incline Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Easier push-up variation with hands elevated.', instructions: ['Place hands on elevated surface', 'Body in straight line', 'Lower chest to surface', 'Push up to extension'], commonMistakes: ['Surface too high/low', 'Hips sagging', 'Not full ROM'], musclesWorked: ['Lower Pectoralis', 'Triceps'], videoPrompt: 'Incline Push-Up tutorial.', sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'dips-calisthenics', name: 'Dips', muscleGroup: 'Chest', equipment: 'Parallel Bars', level: 'intermediate', type: 'calisthenics', description: 'Upper body mass builder targeting chest and triceps.', instructions: ['Grip parallel bars', 'Lower body with control', 'Push up to lockout', 'Lean forward for chest focus'], commonMistakes: ['Going too deep', 'Not locking out', 'Swinging'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], videoPrompt: 'Dips calisthenics tutorial.', videoUrl: '/videos/dips-calisthenics.mp4', sets: 3, reps: '10-15', restSeconds: 75 },
  { id: 'chest-squeeze-press', name: 'Chest Squeeze Press', muscleGroup: 'Chest', equipment: 'Dumbbells', level: 'advanced', type: 'gym', description: 'Pressing while squeezing dumbbells together for peak contraction.', instructions: ['Press dumbbells together at chest', 'Press up maintaining squeeze', 'Keep tension throughout', 'Lower with control'], commonMistakes: ['Not enough squeeze', 'Losing contact between DBs', 'Using momentum'], musclesWorked: ['Inner Pectoralis', 'Triceps'], videoPrompt: 'Chest Squeeze Press in gym.', sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'plate-press', name: 'Plate Press', muscleGroup: 'Chest', equipment: 'Weight Plate', level: 'advanced', type: 'gym', description: 'Squeezing a plate between hands for constant chest activation.', instructions: ['Hold plate between palms at chest', 'Squeeze hard and press forward', 'Extend arms fully', 'Return with continuous squeeze'], commonMistakes: ['Not enough squeeze pressure', 'Dropping plate', 'Rushing reps'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], videoPrompt: 'Plate Press in gym.', sets: 3, reps: '12-15', restSeconds: 45 },
  { id: 'standing-chest-press', name: 'Standing Cable Chest Press', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'intermediate', type: 'gym', description: 'Pressing from standing engages core and stabilizers.', instructions: ['Set cables at chest height', 'Step forward for tension', 'Press handles forward', 'Return with control'], commonMistakes: ['Too much weight', 'Not enough step forward', 'Losing core stability'], musclesWorked: ['Pectoralis Major', 'Core', 'Triceps'], videoPrompt: 'Standing Cable Chest Press.', sets: 3, reps: '10-12', restSeconds: 60 },

  // ===== BACK - GYM =====
  { id: 'deadlift', name: 'Deadlift', muscleGroup: 'Back', equipment: 'Barbell', level: 'advanced', type: 'gym', description: 'The ultimate compound lift for total posterior chain.', instructions: ['Stand with feet hip-width apart', 'Grip bar just outside knees', 'Drive through heels, keep bar close', 'Lock out hips at top'], commonMistakes: ['Rounding lower back', 'Bar drifting forward', 'Jerking the weight up'], musclesWorked: ['Erector Spinae', 'Glutes', 'Hamstrings', 'Traps', 'Lats'], videoPrompt: 'Deadlift in a modern gym.', videoUrl: '/videos/deadlift.mp4', sets: 4, reps: '5-8', restSeconds: 120 },
  { id: 'barbell-row', name: 'Barbell Row', muscleGroup: 'Back', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Builds thick back muscles and improves posture.', instructions: ['Hinge at hips, slight knee bend', 'Pull bar to lower chest', 'Squeeze shoulder blades', 'Lower with control'], commonMistakes: ['Standing too upright', 'Using momentum', 'Not squeezing at top'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids', 'Biceps'], videoPrompt: 'Barbell Row in a modern gym.', videoUrl: '/videos/barbell-row.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroup: 'Back', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Excellent for building wide lats and V-taper.', instructions: ['Grip bar wider than shoulders', 'Pull down to upper chest', 'Lean back slightly', 'Control the return'], commonMistakes: ['Pulling behind neck', 'Too much body momentum', 'Grip too narrow'], musclesWorked: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoids'], videoPrompt: 'Lat Pulldown in a modern gym.', videoUrl: '/videos/lat-pulldown.mp4', sets: 4, reps: '10-12', restSeconds: 75 },

  // ===== SHOULDERS - GYM =====
  { id: 'overhead-press', name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'The premier shoulder mass builder.', instructions: ['Start with bar at collar bone', 'Press overhead to lockout', 'Keep core tight', 'Lower with control'], commonMistakes: ['Excessive back arch', 'Not locking out', 'Pressing in front of face'], musclesWorked: ['Anterior Deltoids', 'Lateral Deltoids', 'Triceps', 'Upper Chest'], videoPrompt: 'Overhead Press in a modern gym.', videoUrl: '/videos/overhead-press.mp4', sets: 4, reps: '8-10', restSeconds: 90 },
  { id: 'lateral-raise', name: 'Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Isolation for wide, capped deltoids.', instructions: ['Hold dumbbells at sides', 'Raise arms to shoulder height', 'Lead with elbows', 'Lower slowly'], commonMistakes: ['Using too much weight', 'Swinging body', 'Raising above shoulders'], musclesWorked: ['Lateral Deltoids'], videoPrompt: 'Lateral Raise in a modern gym.', videoUrl: '/videos/lateral-raise.mp4', sets: 4, reps: '12-15', restSeconds: 60 },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'Shoulders', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Essential for rear delts and shoulder health.', instructions: ['Set cable at face height', 'Pull rope to face level', 'Externally rotate at end', 'Squeeze rear delts'], commonMistakes: ['Cable set too low', 'Not externally rotating', 'Too much weight'], musclesWorked: ['Rear Deltoids', 'Rotator Cuff', 'Upper Traps'], videoPrompt: 'Face Pull in a modern gym.', videoUrl: '/videos/face-pull.mp4', sets: 3, reps: '15-20', restSeconds: 45 },

  // ===== ARMS - GYM =====
  { id: 'barbell-curl', name: 'Barbell Curl', muscleGroup: 'Arms', equipment: 'Barbell', level: 'beginner', type: 'gym', description: 'Classic bicep builder for peak and mass.', instructions: ['Stand with shoulder-width grip', 'Curl bar up keeping elbows pinned', 'Squeeze biceps at top', 'Lower with control'], commonMistakes: ['Swinging body', 'Moving elbows forward', 'Not full ROM'], musclesWorked: ['Biceps Brachii', 'Brachialis'], videoPrompt: 'Barbell Curl in a modern gym.', videoUrl: '/videos/barbell-curl.mp4', sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'skull-crusher', name: 'Skull Crusher', muscleGroup: 'Arms', equipment: 'EZ Bar, Bench', level: 'intermediate', type: 'gym', description: 'Targets all three heads of the triceps.', instructions: ['Lie on bench holding EZ bar', 'Lower bar toward forehead', 'Keep upper arms vertical', 'Extend arms to lockout'], commonMistakes: ['Elbows flaring out', 'Moving upper arms', 'Going too heavy'], musclesWorked: ['Triceps (all heads)'], videoPrompt: 'Skull Crusher in a modern gym.', videoUrl: '/videos/skull-crusher.mp4', sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroup: 'Arms', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Builds brachialis and forearms for thicker arms.', instructions: ['Hold dumbbells with neutral grip', 'Curl up keeping palms facing each other', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Swinging body', 'Rotating wrists', 'Going too fast'], musclesWorked: ['Brachialis', 'Brachioradialis', 'Biceps'], videoPrompt: 'Hammer Curl in a modern gym.', videoUrl: '/videos/hammer-curl.mp4', sets: 3, reps: '10-12', restSeconds: 60 },

  // ===== LEGS - GYM =====
  { id: 'barbell-squat', name: 'Barbell Squat', muscleGroup: 'Legs', equipment: 'Barbell, Squat Rack', level: 'intermediate', type: 'gym', description: 'The king of all exercises. Builds massive legs.', instructions: ['Bar on upper traps', 'Feet shoulder-width apart', 'Squat to parallel or below', 'Drive through heels to stand'], commonMistakes: ['Knees caving in', 'Not hitting depth', 'Leaning too far forward'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], videoPrompt: 'Barbell Squat in a modern gym.', videoUrl: '/videos/barbell-squat.mp4', sets: 4, reps: '6-10', restSeconds: 120 },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'Legs', equipment: 'Leg Press Machine', level: 'beginner', type: 'gym', description: 'Machine-based quad builder with less spinal load.', instructions: ['Sit with back flat against pad', 'Place feet shoulder-width on platform', 'Lower until 90 degree knee angle', 'Press up without locking knees'], commonMistakes: ['Hips lifting off pad', 'Locking out knees', 'Too narrow foot placement'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'], videoPrompt: 'Leg Press in a modern gym.', videoUrl: '/videos/leg-press.mp4', sets: 4, reps: '10-12', restSeconds: 90 },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroup: 'Legs', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Best exercise for hamstring and glute development.', instructions: ['Hold bar at hip level', 'Hinge at hips pushing them back', 'Keep slight knee bend', 'Feel stretch in hamstrings, reverse'], commonMistakes: ['Rounding back', 'Bending knees too much', 'Not hinging enough'], musclesWorked: ['Hamstrings', 'Glutes', 'Erector Spinae'], videoPrompt: 'Romanian Deadlift in a modern gym.', videoUrl: '/videos/romanian-deadlift.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'leg-curl', name: 'Leg Curl', muscleGroup: 'Legs', equipment: 'Leg Curl Machine', level: 'beginner', type: 'gym', description: 'Isolates hamstrings for balanced leg development.', instructions: ['Lie face down on machine', 'Curl weight toward glutes', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Lifting hips off pad', 'Using momentum', 'Not full ROM'], musclesWorked: ['Hamstrings'], videoPrompt: 'Leg Curl in a modern gym.', videoUrl: '/videos/leg-curl.mp4', sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'calf-raise', name: 'Standing Calf Raise', muscleGroup: 'Legs', equipment: 'Calf Raise Machine', level: 'beginner', type: 'gym', description: 'Builds defined calves with full range of motion.', instructions: ['Stand on platform with balls of feet', 'Rise up onto toes', 'Pause at top', 'Lower below platform level'], commonMistakes: ['Bouncing reps', 'Not enough ROM', 'Going too fast'], musclesWorked: ['Gastrocnemius', 'Soleus'], videoPrompt: 'Standing Calf Raise in a modern gym.', videoUrl: '/videos/calf-raise.mp4', sets: 4, reps: '15-20', restSeconds: 45 },

  // ===== ABS - GYM =====
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'Abs', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Weighted ab exercise for thick, defined abs.', instructions: ['Kneel in front of cable machine', 'Hold rope behind head', 'Crunch down bringing elbows to knees', 'Control the return'], commonMistakes: ['Hip flexion instead of spinal flexion', 'Too much weight', 'Not controlling negative'], musclesWorked: ['Rectus Abdominis'], videoPrompt: 'Cable Crunch in a modern gym.', videoUrl: '/videos/cable-crunch.mp4', sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'Abs', equipment: 'Pull-up Bar', level: 'intermediate', type: 'gym', description: 'Advanced lower ab exercise.', instructions: ['Hang from pull-up bar', 'Raise legs to parallel or higher', 'Control the lowering phase', 'Avoid swinging'], commonMistakes: ['Using momentum', 'Not raising high enough', 'Swinging'], musclesWorked: ['Lower Abs', 'Hip Flexors'], videoPrompt: 'Hanging Leg Raise in a modern gym.', videoUrl: '/videos/hanging-leg-raise.mp4', sets: 3, reps: '10-15', restSeconds: 60 },

  // ===== GLUTES - GYM =====
  { id: 'hip-thrust', name: 'Hip Thrust', muscleGroup: 'Glutes', equipment: 'Barbell, Bench', level: 'intermediate', type: 'gym', description: 'The #1 glute builder. Maximum glute activation.', instructions: ['Upper back on bench', 'Bar across hips with pad', 'Drive hips up to full extension', 'Squeeze glutes at top'], commonMistakes: ['Hyperextending lower back', 'Not full hip extension', 'Feet too far forward'], musclesWorked: ['Gluteus Maximus', 'Hamstrings'], videoPrompt: 'Hip Thrust in a modern gym.', videoUrl: '/videos/hip-thrust.mp4', sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroup: 'Glutes', equipment: 'Dumbbells, Bench', level: 'intermediate', type: 'gym', description: 'Unilateral exercise for glutes and imbalance correction.', instructions: ['Rear foot on bench', 'Lower until front thigh parallel', 'Drive through front heel', 'Keep torso upright'], commonMistakes: ['Front knee past toe', 'Leaning too far forward', 'Back foot too far from bench'], musclesWorked: ['Glutes', 'Quadriceps', 'Hamstrings'], videoPrompt: 'Bulgarian Split Squat in a modern gym.', videoUrl: '/videos/bulgarian-split-squat.mp4', sets: 3, reps: '10-12 each', restSeconds: 75 },

  // ===== CALISTHENICS - OTHER =====
  { id: 'pull-up', name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'intermediate', type: 'calisthenics', description: 'The ultimate back builder using bodyweight.', instructions: ['Grip bar slightly wider than shoulders', 'Pull until chin clears bar', 'Lower with full control', 'Start from dead hang'], commonMistakes: ['Kipping or swinging', 'Not going to full hang', 'Chin not clearing bar'], musclesWorked: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoids', 'Core'], videoPrompt: 'Pull-Up calisthenics tutorial.', videoUrl: '/videos/pull-up.mp4', sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'handstand-push-up', name: 'Handstand Push-Up', muscleGroup: 'Shoulders', equipment: 'Wall', level: 'advanced', type: 'calisthenics', description: 'Advanced shoulder exercise requiring strength and balance.', instructions: ['Kick up to handstand against wall', 'Lower head toward floor', 'Press back up to full extension', 'Keep core tight'], commonMistakes: ['Not going deep enough', 'Arching back', 'Kicking up unsafely'], musclesWorked: ['Deltoids', 'Triceps', 'Upper Chest', 'Core'], videoPrompt: 'Handstand Push-Up tutorial.', videoUrl: '/videos/handstand-push-up.mp4', sets: 3, reps: '5-8', restSeconds: 120 },
  { id: 'muscle-up', name: 'Muscle-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'advanced', type: 'calisthenics', description: 'The pinnacle of upper body calisthenics.', instructions: ['Start from dead hang', 'Explosive pull above the bar', 'Transition to dip position', 'Press to lockout above bar'], commonMistakes: ['Not enough explosive pull', 'Chicken winging', 'Kipping too much'], musclesWorked: ['Lats', 'Chest', 'Triceps', 'Biceps', 'Core'], videoPrompt: 'Muscle-Up calisthenics tutorial.', videoUrl: '/videos/muscle-up.mp4', sets: 3, reps: '3-5', restSeconds: 120 },
  { id: 'l-sit', name: 'L-Sit', muscleGroup: 'Abs', equipment: 'Parallel Bars or Floor', level: 'advanced', type: 'calisthenics', description: 'Isometric core exercise building incredible ab strength.', instructions: ['Support body on hands', 'Extend legs straight in front', 'Hold position with legs parallel to floor', 'Keep shoulders depressed'], commonMistakes: ['Bending knees', 'Shoulders rising', 'Not holding long enough'], musclesWorked: ['Abs', 'Hip Flexors', 'Triceps', 'Shoulders'], videoPrompt: 'L-Sit calisthenics tutorial.', videoUrl: '/videos/l-sit.mp4', sets: 3, reps: '15-30s hold', restSeconds: 90 },
  { id: 'pistol-squat', name: 'Pistol Squat', muscleGroup: 'Legs', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Single-leg squat requiring extreme strength and balance.', instructions: ['Stand on one leg', 'Extend other leg forward', 'Squat down to full depth', 'Stand back up without assistance'], commonMistakes: ['Heel lifting', 'Losing balance', 'Not going deep enough'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], videoPrompt: 'Pistol Squat tutorial.', videoUrl: '/videos/pistol-squat.mp4', sets: 3, reps: '5-8 each', restSeconds: 90 },
  { id: 'dragon-flag', name: 'Dragon Flag', muscleGroup: 'Abs', equipment: 'Bench', level: 'advanced', type: 'calisthenics', description: "Bruce Lee's signature ab exercise. Builds steel-like core.", instructions: ['Lie on bench, grip behind head', 'Raise entire body to vertical', 'Lower body keeping rigid', 'Only shoulder blades touch bench'], commonMistakes: ['Bending at hips', 'Going too fast', 'Not enough control'], musclesWorked: ['Entire Core', 'Hip Flexors', 'Lower Back'], videoPrompt: 'Dragon Flag calisthenics tutorial.', videoUrl: '/videos/dragon-flag.mp4', sets: 3, reps: '5-8', restSeconds: 90 },
  { id: 'planche-lean', name: 'Planche Lean', muscleGroup: 'Shoulders', equipment: 'Floor', level: 'advanced', type: 'calisthenics', description: 'Builds shoulder and wrist strength for planche.', instructions: ['Start in push-up position', 'Lean forward shifting weight to hands', 'Keep arms straight', 'Hold the lean position'], commonMistakes: ['Bending arms', 'Not leaning far enough', 'Hips too high'], musclesWorked: ['Anterior Deltoids', 'Core', 'Wrist Flexors'], videoPrompt: 'Planche Lean tutorial.', videoUrl: '/videos/planche-lean.mp4', sets: 3, reps: '15-20s hold', restSeconds: 60 },
  { id: 'australian-pull-up', name: 'Australian Pull-Up', muscleGroup: 'Back', equipment: 'Low Bar', level: 'beginner', type: 'calisthenics', description: 'Horizontal pull. Great progression toward full pull-ups.', instructions: ['Hang under a low bar', 'Pull chest to bar', 'Keep body in straight line', 'Lower with control'], commonMistakes: ['Hips sagging', 'Not pulling to chest', 'Using momentum'], musclesWorked: ['Lats', 'Rhomboids', 'Biceps', 'Rear Deltoids'], videoPrompt: 'Australian Pull-Up tutorial.', videoUrl: '/videos/australian-pull-up.mp4', sets: 3, reps: '12-15', restSeconds: 60 },
];

export const getExercisesByMuscleGroup = (group: string) => exercises.filter(e => e.muscleGroup === group);
export const getExercisesByType = (type: 'gym' | 'calisthenics') => exercises.filter(e => e.type === type);
export const getExerciseById = (id: string) => exercises.find(e => e.id === id);
