import { Exercise } from './types';
import { videoExercises } from './videoExercises';

export const exercises: Exercise[] = [
  // ===== CHEST - GYM (14 exercises) =====
  { id: 'bench-press', name: 'Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Bench', level: 'beginner', type: 'gym', description: 'The king of chest exercises. Builds mass and strength in the pectorals.', instructions: ['Lie flat on bench with feet on floor', 'Grip barbell slightly wider than shoulders', 'Lower bar to mid-chest with control', 'Press up explosively to lockout'], commonMistakes: ['Bouncing bar off chest', 'Flaring elbows too wide', 'Lifting hips off bench'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids', 'Triceps'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'incline-bench', name: 'Incline Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets the upper chest for complete development.', instructions: ['Set bench to 30-45 degrees', 'Grip barbell slightly wider than shoulders', 'Lower bar to upper chest', 'Press up to lockout'], commonMistakes: ['Bench angle too steep', 'Bouncing off chest', 'Flaring elbows'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'decline-bench', name: 'Decline Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Decline Bench', level: 'intermediate', type: 'gym', description: 'Emphasizes the lower chest fibers.', instructions: ['Secure feet on decline bench', 'Grip barbell slightly wider than shoulders', 'Lower bar to lower chest', 'Press up to lockout'], commonMistakes: ['Not securing feet', 'Too much decline', 'Bouncing bar'], musclesWorked: ['Lower Pectoralis', 'Triceps', 'Anterior Deltoids'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'flat-db-fly', name: 'Flat Dumbbell Fly', muscleGroup: 'Chest', equipment: 'Dumbbells, Bench', level: 'beginner', type: 'gym', description: 'Isolation movement stretching the chest fibers for width.', instructions: ['Lie flat with dumbbells above chest', 'Open arms wide in arc motion', 'Feel stretch in chest', 'Squeeze back to top'], commonMistakes: ['Going too deep', 'Bending elbows too much', 'Using momentum'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'incline-db-fly', name: 'Incline Dumbbell Fly', muscleGroup: 'Chest', equipment: 'Dumbbells, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets upper chest with isolation.', instructions: ['Set bench to 30-45 degrees', 'Open arms wide in arc motion', 'Feel stretch in upper chest', 'Squeeze back to top'], commonMistakes: ['Bench too steep', 'Not enough ROM', 'Too heavy'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'peck-deck', name: 'Peck Deck', muscleGroup: 'Chest', equipment: 'Machine', level: 'beginner', type: 'gym', description: 'Machine chest isolation with constant tension.', instructions: ['Sit with back against pad', 'Grip handles at chest level', 'Bring handles together', 'Squeeze chest at center'], commonMistakes: ['Too much weight', 'Not full ROM', 'Shrugging shoulders'], musclesWorked: ['Pectoralis Major'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'incline-db-press', name: 'Incline Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbells, Incline Bench', level: 'intermediate', type: 'gym', description: 'Targets the upper chest for complete pectoral development.', instructions: ['Set bench to 30-45 degrees', 'Press dumbbells up from shoulder level', 'Squeeze at the top', 'Lower with control'], commonMistakes: ['Bench angle too steep', 'Not full range of motion', 'Using momentum'], musclesWorked: ['Upper Pectoralis', 'Anterior Deltoids', 'Triceps'], sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'cable-fly', name: 'Cable Fly', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Isolation exercise for chest with constant tension.', instructions: ['Stand between cable stations', 'Slight bend in elbows', 'Bring handles together in arc motion', 'Squeeze chest at center'], commonMistakes: ['Too much elbow bend', 'Using too much weight', 'Leaning too far forward'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'cable-crossover', name: 'Cable Crossover', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'intermediate', type: 'gym', description: 'Full range chest isolation with constant cable tension.', instructions: ['Set cables at high position', 'Step forward, slight lean', 'Bring hands together in low arc', 'Squeeze chest at bottom'], commonMistakes: ['Too much weight', 'Not enough lean', 'Rushing reps'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'dips-chest', name: 'Chest Dips', muscleGroup: 'Chest', equipment: 'Dip Station', level: 'intermediate', type: 'gym', description: 'Compound movement targeting lower chest.', instructions: ['Lean forward on dip bars', 'Lower body until upper arms parallel', 'Push up explosively', 'Keep elbows slightly flared'], commonMistakes: ['Going too deep', 'Not leaning forward', 'Swinging body'], musclesWorked: ['Lower Pectoralis', 'Triceps', 'Anterior Deltoids'], sets: 3, reps: '10-15', restSeconds: 75 },
  { id: 'press-machine', name: 'Chest Press Machine', muscleGroup: 'Chest', equipment: 'Machine', level: 'beginner', type: 'gym', description: 'Machine-based pressing for controlled chest training.', instructions: ['Sit with back flat', 'Grip handles at chest level', 'Press forward to extension', 'Return with control'], commonMistakes: ['Seat too high/low', 'Not full ROM', 'Locking out aggressively'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'db-press-flat', name: 'Flat Dumbbell Press', muscleGroup: 'Chest', equipment: 'Dumbbells, Bench', level: 'intermediate', type: 'gym', description: 'Allows greater ROM than barbell for chest development.', instructions: ['Lie flat with dumbbells at chest', 'Press up to lockout', 'Lower with control', 'Squeeze at top'], commonMistakes: ['Dumbbells too wide', 'Not enough control', 'Arching excessively'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], sets: 4, reps: '8-12', restSeconds: 75 },
  { id: 'smith-bench', name: 'Smith Machine Bench Press', muscleGroup: 'Chest', equipment: 'Smith Machine', level: 'intermediate', type: 'gym', description: 'Guided bench press for controlled chest training.', instructions: ['Lie under Smith machine bar', 'Grip slightly wider than shoulders', 'Unrack and lower to chest', 'Press up to lockout'], commonMistakes: ['Bar path too forward/back', 'Not enough ROM', 'Relying on the machine'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'close-grip-bench', name: 'Close-Grip Bench Press', muscleGroup: 'Chest', equipment: 'Barbell, Bench', level: 'intermediate', type: 'gym', description: 'Targets inner chest and triceps with narrow grip.', instructions: ['Grip barbell shoulder-width or narrower', 'Lower to lower chest', 'Press up keeping elbows close', 'Lockout at top'], commonMistakes: ['Grip too narrow', 'Flaring elbows', 'Bouncing off chest'], musclesWorked: ['Inner Pectoralis', 'Triceps'], sets: 4, reps: '8-12', restSeconds: 75 },

  // ===== CHEST - CALISTHENICS (16 exercises) =====
  { id: 'push-up', name: 'Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Fundamental bodyweight chest exercise.', instructions: ['Hands shoulder-width apart', 'Body in straight line', 'Lower chest to floor', 'Push up to full extension'], commonMistakes: ['Hips sagging', 'Elbows flaring 90°', 'Not full ROM'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids', 'Core'], sets: 4, reps: '15-25', restSeconds: 60 },
  { id: 'diamond-push-up', name: 'Diamond Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Narrow hand placement targeting inner chest and triceps.', instructions: ['Form diamond shape with hands', 'Lower chest to hands', 'Push up to full extension', 'Keep elbows close to body'], commonMistakes: ['Hands too far forward', 'Flaring elbows', 'Hips sagging'], musclesWorked: ['Inner Pectoralis', 'Triceps', 'Core'], sets: 3, reps: '10-15', restSeconds: 60 },
  { id: 'decline-push-up', name: 'Decline Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Feet elevated to target upper chest.', instructions: ['Place feet on elevated surface', 'Hands shoulder-width on floor', 'Lower chest to floor', 'Push up with control'], commonMistakes: ['Too much elevation', 'Hips sagging', 'Not full ROM'], musclesWorked: ['Upper Pectoralis', 'Triceps', 'Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'archer-push-up', name: 'Archer Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Unilateral push-up variation for advanced chest training.', instructions: ['Wide hand placement', 'Shift weight to one arm', 'Lower to working arm side', 'Push back up and alternate'], commonMistakes: ['Not enough weight shift', 'Rushing reps', 'Collapsing core'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], sets: 3, reps: '6-8 each', restSeconds: 90 },
  { id: 'explosive-push-up', name: 'Explosive Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Plyometric push-up for power and fast-twitch fiber activation.', instructions: ['Start in push-up position', 'Lower with control', 'Explode up lifting hands off floor', 'Land softly and repeat'], commonMistakes: ['Not enough explosion', 'Poor landing mechanics', 'Hips dropping'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], sets: 3, reps: '8-12', restSeconds: 90 },
  { id: 'hindu-push-up', name: 'Hindu Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Flowing movement working chest, shoulders, and flexibility.', instructions: ['Start in downward dog', 'Swoop down and forward', 'Push through to cobra position', 'Return to downward dog'], commonMistakes: ['Not enough swoop', 'Rushing movement', 'Not using full ROM'], musclesWorked: ['Pectoralis Major', 'Deltoids', 'Triceps', 'Core'], sets: 3, reps: '10-15', restSeconds: 60 },
  { id: 'pseudo-planche-push-up', name: 'Pseudo Planche Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Hands turned back, leaning forward for extreme chest and shoulder work.', instructions: ['Place hands by hips, fingers pointing back', 'Lean forward significantly', 'Lower chest to floor', 'Push up maintaining lean'], commonMistakes: ['Not enough lean', 'Fingers pointing forward', 'Losing core tension'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids', 'Core'], sets: 3, reps: '6-10', restSeconds: 90 },
  { id: 'pause-push-up', name: 'Pause Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Pausing at the bottom eliminates momentum for maximum tension.', instructions: ['Lower to bottom position', 'Pause for 2-3 seconds', 'Push up explosively', 'Maintain body alignment'], commonMistakes: ['Not pausing long enough', 'Losing tension at bottom', 'Hips sagging'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], sets: 3, reps: '8-12', restSeconds: 60 },
  { id: 'weighted-push-up', name: 'Weighted Push-Up', muscleGroup: 'Chest', equipment: 'Weight Plate', level: 'advanced', type: 'calisthenics', description: 'Added resistance for progressive overload on push-ups.', instructions: ['Place weight plate on upper back', 'Perform standard push-up', 'Maintain alignment with weight', 'Control the descent'], commonMistakes: ['Weight sliding', 'Losing form', 'Too much weight'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core'], sets: 4, reps: '8-12', restSeconds: 75 },
  { id: 'ring-push-up', name: 'Ring Push-Up', muscleGroup: 'Chest', equipment: 'Gymnastic Rings', level: 'advanced', type: 'calisthenics', description: 'Unstable surface forces greater stabilizer activation.', instructions: ['Set rings at low height', 'Grip rings in push-up position', 'Lower with control', 'Push up and turn rings out at top'], commonMistakes: ['Rings too high', 'Not stabilizing', 'Rushing reps'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core', 'Stabilizers'], sets: 3, reps: '8-12', restSeconds: 75 },
  { id: 'one-arm-push-up', name: 'One-Arm Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Ultimate unilateral chest and core challenge.', instructions: ['Wide stance for balance', 'One hand on floor, other behind back', 'Lower with control', 'Push up maintaining alignment'], commonMistakes: ['Rotating hips', 'Not enough depth', 'Stance too narrow'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Core', 'Obliques'], sets: 3, reps: '3-5 each', restSeconds: 120 },
  { id: 'incline-push-up', name: 'Incline Push-Up', muscleGroup: 'Chest', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Easier push-up variation with hands elevated.', instructions: ['Place hands on elevated surface', 'Body in straight line', 'Lower chest to surface', 'Push up to extension'], commonMistakes: ['Surface too high/low', 'Hips sagging', 'Not full ROM'], musclesWorked: ['Lower Pectoralis', 'Triceps'], sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'dips-calisthenics', name: 'Dips', muscleGroup: 'Chest', equipment: 'Parallel Bars', level: 'intermediate', type: 'calisthenics', description: 'Upper body mass builder targeting chest and triceps.', instructions: ['Grip parallel bars', 'Lower body with control', 'Push up to lockout', 'Lean forward for chest focus'], commonMistakes: ['Going too deep', 'Not locking out', 'Swinging'], musclesWorked: ['Pectoralis Major', 'Triceps', 'Anterior Deltoids'], sets: 3, reps: '10-15', restSeconds: 75 },
  { id: 'chest-squeeze-press', name: 'Chest Squeeze Press', muscleGroup: 'Chest', equipment: 'Dumbbells', level: 'advanced', type: 'gym', description: 'Pressing while squeezing dumbbells together for peak contraction.', instructions: ['Press dumbbells together at chest', 'Press up maintaining squeeze', 'Keep tension throughout', 'Lower with control'], commonMistakes: ['Not enough squeeze', 'Losing contact between DBs', 'Using momentum'], musclesWorked: ['Inner Pectoralis', 'Triceps'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'plate-press', name: 'Plate Press', muscleGroup: 'Chest', equipment: 'Weight Plate', level: 'advanced', type: 'gym', description: 'Squeezing a plate between hands for constant chest activation.', instructions: ['Hold plate between palms at chest', 'Squeeze hard and press forward', 'Extend arms fully', 'Return with continuous squeeze'], commonMistakes: ['Not enough squeeze pressure', 'Dropping plate', 'Rushing reps'], musclesWorked: ['Pectoralis Major', 'Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 45 },
  { id: 'standing-chest-press', name: 'Standing Cable Chest Press', muscleGroup: 'Chest', equipment: 'Cable Machine', level: 'intermediate', type: 'gym', description: 'Pressing from standing engages core and stabilizers.', instructions: ['Set cables at chest height', 'Step forward for tension', 'Press handles forward', 'Return with control'], commonMistakes: ['Too much weight', 'Not enough step forward', 'Losing core stability'], musclesWorked: ['Pectoralis Major', 'Core', 'Triceps'], sets: 3, reps: '10-12', restSeconds: 60 },

  // ===== BACK - GYM (15 exercises) =====
  { id: 'deadlift', name: 'Deadlift', muscleGroup: 'Back', equipment: 'Barbell', level: 'advanced', type: 'gym', description: 'The ultimate compound lift for total posterior chain.', instructions: ['Stand with feet hip-width apart', 'Grip bar just outside knees', 'Drive through heels, keep bar close', 'Lock out hips at top'], commonMistakes: ['Rounding lower back', 'Bar drifting forward', 'Jerking the weight up'], musclesWorked: ['Erector Spinae', 'Glutes', 'Hamstrings', 'Traps', 'Lats'], sets: 4, reps: '5-8', restSeconds: 120 },
  { id: 'barbell-row', name: 'Barbell Row', muscleGroup: 'Back', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Builds thick back muscles and improves posture.', instructions: ['Hinge at hips, slight knee bend', 'Pull bar to lower chest', 'Squeeze shoulder blades', 'Lower with control'], commonMistakes: ['Standing too upright', 'Using momentum', 'Not squeezing at top'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids', 'Biceps'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'lat-pulldown', name: 'Lat Pulldown', muscleGroup: 'Back', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Excellent for building wide lats and V-taper.', instructions: ['Grip bar wider than shoulders', 'Pull down to upper chest', 'Lean back slightly', 'Control the return'], commonMistakes: ['Pulling behind neck', 'Too much body momentum', 'Grip too narrow'], musclesWorked: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoids'], sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'db-row', name: 'Dumbbell Row', muscleGroup: 'Back', equipment: 'Dumbbell, Bench', level: 'beginner', type: 'gym', description: 'Unilateral back builder for thickness and symmetry.', instructions: ['One knee and hand on bench', 'Row dumbbell to hip', 'Squeeze shoulder blade at top', 'Lower with control'], commonMistakes: ['Rotating torso', 'Using momentum', 'Not full ROM'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Biceps'], sets: 4, reps: '10-12 each', restSeconds: 60 },
  { id: 'seated-cable-row', name: 'Seated Cable Row', muscleGroup: 'Back', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Builds mid-back thickness with constant tension.', instructions: ['Sit with feet on platform', 'Pull handle to lower chest', 'Squeeze shoulder blades together', 'Extend arms with control'], commonMistakes: ['Leaning too far back', 'Rounding back', 'Using body momentum'], musclesWorked: ['Rhomboids', 'Latissimus Dorsi', 'Biceps', 'Rear Deltoids'], sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 't-bar-row', name: 'T-Bar Row', muscleGroup: 'Back', equipment: 'T-Bar', level: 'intermediate', type: 'gym', description: 'Thick back builder focusing on mid-back.', instructions: ['Stand over T-bar with feet wide', 'Grip handle with both hands', 'Pull to chest keeping back flat', 'Squeeze at top'], commonMistakes: ['Too upright posture', 'Rounding back', 'Using momentum'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids', 'Biceps'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'pendlay-row', name: 'Pendlay Row', muscleGroup: 'Back', equipment: 'Barbell', level: 'advanced', type: 'gym', description: 'Strict row from the floor for maximum back power.', instructions: ['Bar on floor, bend over completely', 'Explosive pull to lower chest', 'Lower bar back to floor each rep', 'Reset position between reps'], commonMistakes: ['Not touching floor', 'Standing up during pull', 'Rounding back'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Erector Spinae'], sets: 4, reps: '6-8', restSeconds: 90 },
  { id: 'close-grip-pulldown', name: 'Close-Grip Pulldown', muscleGroup: 'Back', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Targets lower lats for thickness.', instructions: ['Use V-handle attachment', 'Pull down to upper chest', 'Squeeze lats at bottom', 'Control the return'], commonMistakes: ['Leaning too far back', 'Using too much weight', 'Not squeezing'], musclesWorked: ['Lower Lats', 'Biceps', 'Rhomboids'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'straight-arm-pulldown', name: 'Straight-Arm Pulldown', muscleGroup: 'Back', equipment: 'Cable Machine', level: 'intermediate', type: 'gym', description: 'Lat isolation with no bicep involvement.', instructions: ['Stand facing cable machine', 'Keep arms straight', 'Pull bar down to thighs', 'Squeeze lats hard at bottom'], commonMistakes: ['Bending elbows', 'Using too much weight', 'Not controlling negative'], musclesWorked: ['Latissimus Dorsi', 'Teres Major'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'chest-supported-row', name: 'Chest-Supported Row', muscleGroup: 'Back', equipment: 'Incline Bench, Dumbbells', level: 'beginner', type: 'gym', description: 'Eliminates cheating for strict back isolation.', instructions: ['Lie face down on incline bench', 'Row dumbbells up to sides', 'Squeeze shoulder blades', 'Lower with control'], commonMistakes: ['Not enough squeeze', 'Bench angle wrong', 'Using momentum'], musclesWorked: ['Rhomboids', 'Rear Deltoids', 'Lats'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'rack-pull', name: 'Rack Pull', muscleGroup: 'Back', equipment: 'Barbell, Rack', level: 'intermediate', type: 'gym', description: 'Partial deadlift focusing on upper back and traps.', instructions: ['Set pins at knee height', 'Deadlift from pins to lockout', 'Squeeze traps at top', 'Lower to pins with control'], commonMistakes: ['Rounding upper back', 'Bouncing off pins', 'Going too heavy'], musclesWorked: ['Traps', 'Erector Spinae', 'Lats', 'Glutes'], sets: 4, reps: '6-8', restSeconds: 120 },
  { id: 'meadows-row', name: 'Meadows Row', muscleGroup: 'Back', equipment: 'Barbell (Landmine)', level: 'advanced', type: 'gym', description: 'Unique angle targets lats with a great stretch.', instructions: ['Stand perpendicular to landmine', 'Overhand grip on bar end', 'Row explosively to hip', 'Stretch at bottom'], commonMistakes: ['Not enough stretch', 'Rotating too much', 'Too much weight'], musclesWorked: ['Latissimus Dorsi', 'Rear Deltoids', 'Biceps'], sets: 3, reps: '10-12 each', restSeconds: 60 },
  { id: 'shrug', name: 'Barbell Shrug', muscleGroup: 'Back', equipment: 'Barbell', level: 'beginner', type: 'gym', description: 'Isolates the upper trapezius for thickness.', instructions: ['Hold barbell at hip level', 'Shrug shoulders straight up to ears', 'Hold briefly at top', 'Lower with control'], commonMistakes: ['Rolling shoulders', 'Using too much weight', 'Not holding at top'], musclesWorked: ['Upper Trapezius'], sets: 4, reps: '12-15', restSeconds: 60 },
  { id: 'hyperextension', name: 'Hyperextension', muscleGroup: 'Back', equipment: 'Hyperextension Bench', level: 'beginner', type: 'gym', description: 'Strengthens lower back and spinal erectors.', instructions: ['Position hips on pad', 'Cross arms over chest', 'Lower torso toward floor', 'Raise to parallel with control'], commonMistakes: ['Going too high', 'Using momentum', 'Rounding back'], musclesWorked: ['Erector Spinae', 'Glutes', 'Hamstrings'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'seal-row', name: 'Seal Row', muscleGroup: 'Back', equipment: 'Barbell, Elevated Bench', level: 'intermediate', type: 'gym', description: 'Strict horizontal row with zero cheating possible.', instructions: ['Lie face down on elevated bench', 'Row barbell from floor', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Bench too low', 'Using momentum', 'Not enough squeeze'], musclesWorked: ['Latissimus Dorsi', 'Rhomboids', 'Rear Deltoids'], sets: 4, reps: '8-12', restSeconds: 75 },

  // ===== SHOULDERS - GYM (12 exercises) =====
  { id: 'overhead-press', name: 'Overhead Press', muscleGroup: 'Shoulders', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'The premier shoulder mass builder.', instructions: ['Start with bar at collar bone', 'Press overhead to lockout', 'Keep core tight', 'Lower with control'], commonMistakes: ['Excessive back arch', 'Not locking out', 'Pressing in front of face'], musclesWorked: ['Anterior Deltoids', 'Lateral Deltoids', 'Triceps', 'Upper Chest'], sets: 4, reps: '8-10', restSeconds: 90 },
  { id: 'lateral-raise', name: 'Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Isolation for wide, capped deltoids.', instructions: ['Hold dumbbells at sides', 'Raise arms to shoulder height', 'Lead with elbows', 'Lower slowly'], commonMistakes: ['Using too much weight', 'Swinging body', 'Raising above shoulders'], musclesWorked: ['Lateral Deltoids'], sets: 4, reps: '12-15', restSeconds: 60 },
  { id: 'face-pull', name: 'Face Pull', muscleGroup: 'Shoulders', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Essential for rear delts and shoulder health.', instructions: ['Set cable at face height', 'Pull rope to face level', 'Externally rotate at end', 'Squeeze rear delts'], commonMistakes: ['Cable set too low', 'Not externally rotating', 'Too much weight'], musclesWorked: ['Rear Deltoids', 'Rotator Cuff', 'Upper Traps'], sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'db-shoulder-press', name: 'Dumbbell Shoulder Press', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Versatile pressing for balanced shoulder development.', instructions: ['Sit or stand with dumbbells at shoulders', 'Press overhead to lockout', 'Lower to ear level', 'Keep core engaged'], commonMistakes: ['Arching back', 'Not full ROM', 'Uneven pressing'], musclesWorked: ['Anterior Deltoids', 'Lateral Deltoids', 'Triceps'], sets: 4, reps: '8-12', restSeconds: 75 },
  { id: 'arnold-press', name: 'Arnold Press', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'intermediate', type: 'gym', description: 'Rotating press hitting all three deltoid heads.', instructions: ['Start with palms facing you', 'Rotate palms outward as you press', 'Full lockout overhead', 'Reverse rotation on descent'], commonMistakes: ['Not rotating fully', 'Going too heavy', 'Arching back'], musclesWorked: ['Anterior Deltoids', 'Lateral Deltoids', 'Rear Deltoids'], sets: 3, reps: '10-12', restSeconds: 75 },
  { id: 'front-raise', name: 'Front Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Isolation for front deltoids.', instructions: ['Hold dumbbells in front of thighs', 'Raise arms to shoulder height', 'Keep slight elbow bend', 'Lower with control'], commonMistakes: ['Swinging body', 'Going above shoulder height', 'Too heavy'], musclesWorked: ['Anterior Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'reverse-fly', name: 'Reverse Fly', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Targets rear deltoids for balanced shoulder development.', instructions: ['Bend at hips with flat back', 'Raise dumbbells to sides', 'Squeeze rear delts at top', 'Lower with control'], commonMistakes: ['Using momentum', 'Too heavy', 'Standing too upright'], musclesWorked: ['Rear Deltoids', 'Rhomboids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'cable-lateral-raise', name: 'Cable Lateral Raise', muscleGroup: 'Shoulders', equipment: 'Cable Machine', level: 'intermediate', type: 'gym', description: 'Constant tension lateral raise for capped delts.', instructions: ['Stand sideways to cable', 'Raise arm to shoulder height', 'Control the negative', 'Keep slight elbow bend'], commonMistakes: ['Using body momentum', 'Going too high', 'Bending at waist'], musclesWorked: ['Lateral Deltoids'], sets: 3, reps: '12-15 each', restSeconds: 45 },
  { id: 'upright-row', name: 'Upright Row', muscleGroup: 'Shoulders', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Compound movement for traps and delts.', instructions: ['Hold bar with narrow grip', 'Pull bar up to chin', 'Lead with elbows', 'Lower with control'], commonMistakes: ['Grip too narrow', 'Going too high', 'Shoulder impingement risk'], musclesWorked: ['Lateral Deltoids', 'Upper Traps', 'Biceps'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'machine-shoulder-press', name: 'Machine Shoulder Press', muscleGroup: 'Shoulders', equipment: 'Machine', level: 'beginner', type: 'gym', description: 'Guided shoulder press for safe progression.', instructions: ['Sit with back against pad', 'Grip handles at shoulder height', 'Press up to lockout', 'Lower with control'], commonMistakes: ['Seat too high', 'Arching back', 'Not full ROM'], musclesWorked: ['Anterior Deltoids', 'Lateral Deltoids', 'Triceps'], sets: 3, reps: '10-12', restSeconds: 75 },
  { id: 'lu-raise', name: 'Lu Raise', muscleGroup: 'Shoulders', equipment: 'Dumbbells', level: 'advanced', type: 'gym', description: 'Combined lateral and front raise for total deltoid work.', instructions: ['Raise arms laterally to shoulder height', 'Rotate arms forward to front raise position', 'Lower with control', 'Repeat'], commonMistakes: ['Using momentum', 'Too heavy', 'Incomplete rotation'], musclesWorked: ['Lateral Deltoids', 'Anterior Deltoids', 'Traps'], sets: 3, reps: '8-10', restSeconds: 75 },
  { id: 'behind-neck-press', name: 'Behind Neck Press', muscleGroup: 'Shoulders', equipment: 'Barbell', level: 'advanced', type: 'gym', description: 'Advanced overhead press targeting lateral deltoids.', instructions: ['Lower bar behind neck to ear level', 'Press to lockout', 'Use lighter weight', 'Requires good shoulder mobility'], commonMistakes: ['Going too deep', 'Poor shoulder mobility', 'Too heavy'], musclesWorked: ['Lateral Deltoids', 'Anterior Deltoids', 'Triceps'], sets: 3, reps: '8-10', restSeconds: 90 },

  // ===== BICEPS - GYM (10 exercises) =====
  { id: 'barbell-curl', name: 'Barbell Curl', muscleGroup: 'Arms', equipment: 'Barbell', level: 'beginner', type: 'gym', description: 'Classic bicep builder for peak and mass.', instructions: ['Stand with shoulder-width grip', 'Curl bar up keeping elbows pinned', 'Squeeze biceps at top', 'Lower with control'], commonMistakes: ['Swinging body', 'Moving elbows forward', 'Not full ROM'], musclesWorked: ['Biceps Brachii', 'Brachialis'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'hammer-curl', name: 'Hammer Curl', muscleGroup: 'Arms', equipment: 'Dumbbells', level: 'beginner', type: 'gym', description: 'Builds brachialis and forearms for thicker arms.', instructions: ['Hold dumbbells with neutral grip', 'Curl up keeping palms facing each other', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Swinging body', 'Rotating wrists', 'Going too fast'], musclesWorked: ['Brachialis', 'Brachioradialis', 'Biceps'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'skull-crusher', name: 'Skull Crusher', muscleGroup: 'Arms', equipment: 'EZ Bar, Bench', level: 'intermediate', type: 'gym', description: 'Targets all three heads of the triceps.', instructions: ['Lie on bench holding EZ bar', 'Lower bar toward forehead', 'Keep upper arms vertical', 'Extend arms to lockout'], commonMistakes: ['Elbows flaring out', 'Moving upper arms', 'Going too heavy'], musclesWorked: ['Triceps (all heads)'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'incline-db-curl', name: 'Incline Dumbbell Curl', muscleGroup: 'Arms', equipment: 'Dumbbells, Incline Bench', level: 'intermediate', type: 'gym', description: 'Long head bicep stretch for peak development.', instructions: ['Sit on 45-degree incline bench', 'Let arms hang naturally', 'Curl dumbbells up with supination', 'Lower with control'], commonMistakes: ['Bench not inclined enough', 'Moving elbows forward', 'Swinging'], musclesWorked: ['Biceps Long Head', 'Brachialis'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'preacher-curl', name: 'Preacher Curl', muscleGroup: 'Arms', equipment: 'EZ Bar, Preacher Bench', level: 'beginner', type: 'gym', description: 'Strict curl isolating biceps with no cheating.', instructions: ['Rest arms on preacher pad', 'Curl bar up to shoulders', 'Lower slowly to full extension', 'Keep upper arms on pad'], commonMistakes: ['Not full ROM', 'Lifting elbows off pad', 'Going too fast'], musclesWorked: ['Biceps Short Head', 'Brachialis'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'concentration-curl', name: 'Concentration Curl', muscleGroup: 'Arms', equipment: 'Dumbbell', level: 'beginner', type: 'gym', description: 'Peak contraction curl for bicep definition.', instructions: ['Sit on bench, elbow on inner thigh', 'Curl dumbbell to shoulder', 'Squeeze hard at top', 'Lower slowly'], commonMistakes: ['Using body momentum', 'Not full contraction', 'Elbow moving'], musclesWorked: ['Biceps Brachii'], sets: 3, reps: '10-12 each', restSeconds: 45 },
  { id: 'cable-curl', name: 'Cable Curl', muscleGroup: 'Arms', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Constant tension bicep curl.', instructions: ['Stand facing cable machine', 'Grip bar with underhand grip', 'Curl to shoulders', 'Lower with control'], commonMistakes: ['Leaning back', 'Using too much weight', 'Moving elbows'], musclesWorked: ['Biceps Brachii'], sets: 3, reps: '12-15', restSeconds: 45 },
  { id: 'tricep-pushdown', name: 'Tricep Pushdown', muscleGroup: 'Arms', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Isolation for tricep development.', instructions: ['Stand at cable machine', 'Push rope/bar down to full extension', 'Keep elbows at sides', 'Control the return'], commonMistakes: ['Elbows drifting forward', 'Using body weight', 'Not full extension'], musclesWorked: ['Triceps'], sets: 3, reps: '12-15', restSeconds: 45 },
  { id: 'overhead-tricep-ext', name: 'Overhead Tricep Extension', muscleGroup: 'Arms', equipment: 'Dumbbell', level: 'intermediate', type: 'gym', description: 'Targets the long head of the triceps.', instructions: ['Hold dumbbell overhead with both hands', 'Lower behind head keeping elbows pointing up', 'Extend back to lockout', 'Keep upper arms still'], commonMistakes: ['Flaring elbows', 'Not going deep enough', 'Arching back'], musclesWorked: ['Triceps Long Head'], sets: 3, reps: '10-12', restSeconds: 60 },
  { id: 'close-grip-pushup', name: 'Close-Grip Push-Up', muscleGroup: 'Arms', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Bodyweight tricep builder.', instructions: ['Hands shoulder-width or narrower', 'Keep elbows close to body', 'Lower chest to floor', 'Push up to lockout'], commonMistakes: ['Elbows flaring', 'Hips sagging', 'Hands too close'], musclesWorked: ['Triceps', 'Chest', 'Core'], sets: 3, reps: '12-15', restSeconds: 60 },

  // ===== LEGS - GYM (15 exercises) =====
  { id: 'barbell-squat', name: 'Barbell Squat', muscleGroup: 'Legs', equipment: 'Barbell, Squat Rack', level: 'intermediate', type: 'gym', description: 'The king of all exercises. Builds massive legs.', instructions: ['Bar on upper traps', 'Feet shoulder-width apart', 'Squat to parallel or below', 'Drive through heels to stand'], commonMistakes: ['Knees caving in', 'Not hitting depth', 'Leaning too far forward'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], sets: 4, reps: '6-10', restSeconds: 120 },
  { id: 'leg-press', name: 'Leg Press', muscleGroup: 'Legs', equipment: 'Leg Press Machine', level: 'beginner', type: 'gym', description: 'Machine-based quad builder with less spinal load.', instructions: ['Sit with back flat against pad', 'Place feet shoulder-width on platform', 'Lower until 90 degree knee angle', 'Press up without locking knees'], commonMistakes: ['Hips lifting off pad', 'Locking out knees', 'Too narrow foot placement'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'], sets: 4, reps: '10-12', restSeconds: 90 },
  { id: 'romanian-deadlift', name: 'Romanian Deadlift', muscleGroup: 'Legs', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Best exercise for hamstring and glute development.', instructions: ['Hold bar at hip level', 'Hinge at hips pushing them back', 'Keep slight knee bend', 'Feel stretch in hamstrings, reverse'], commonMistakes: ['Rounding back', 'Bending knees too much', 'Not hinging enough'], musclesWorked: ['Hamstrings', 'Glutes', 'Erector Spinae'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'leg-curl', name: 'Leg Curl', muscleGroup: 'Legs', equipment: 'Leg Curl Machine', level: 'beginner', type: 'gym', description: 'Isolates hamstrings for balanced leg development.', instructions: ['Lie face down on machine', 'Curl weight toward glutes', 'Squeeze at top', 'Lower with control'], commonMistakes: ['Lifting hips off pad', 'Using momentum', 'Not full ROM'], musclesWorked: ['Hamstrings'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'calf-raise', name: 'Standing Calf Raise', muscleGroup: 'Legs', equipment: 'Calf Raise Machine', level: 'beginner', type: 'gym', description: 'Builds defined calves with full range of motion.', instructions: ['Stand on platform with balls of feet', 'Rise up onto toes', 'Pause at top', 'Lower below platform level'], commonMistakes: ['Bouncing reps', 'Not enough ROM', 'Going too fast'], musclesWorked: ['Gastrocnemius', 'Soleus'], sets: 4, reps: '15-20', restSeconds: 45 },
  { id: 'front-squat', name: 'Front Squat', muscleGroup: 'Legs', equipment: 'Barbell, Squat Rack', level: 'advanced', type: 'gym', description: 'Quad-dominant squat with upright torso.', instructions: ['Bar on front delts, cross grip or clean grip', 'Keep elbows high', 'Squat to depth', 'Drive up keeping torso upright'], commonMistakes: ['Elbows dropping', 'Leaning forward', 'Not enough depth'], musclesWorked: ['Quadriceps', 'Core', 'Glutes'], sets: 4, reps: '6-10', restSeconds: 120 },
  { id: 'hack-squat', name: 'Hack Squat', muscleGroup: 'Legs', equipment: 'Hack Squat Machine', level: 'intermediate', type: 'gym', description: 'Machine squat for targeted quad development.', instructions: ['Stand on platform with back against pad', 'Squat down to depth', 'Press up through heels', 'Control the descent'], commonMistakes: ['Not enough depth', 'Knees going too far over toes', 'Bouncing at bottom'], musclesWorked: ['Quadriceps', 'Glutes'], sets: 4, reps: '10-12', restSeconds: 90 },
  { id: 'leg-extension', name: 'Leg Extension', muscleGroup: 'Legs', equipment: 'Leg Extension Machine', level: 'beginner', type: 'gym', description: 'Quad isolation for definition and pump.', instructions: ['Sit with back against pad', 'Extend legs to full lockout', 'Squeeze quads at top', 'Lower with control'], commonMistakes: ['Using momentum', 'Not full extension', 'Going too heavy'], musclesWorked: ['Quadriceps'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'walking-lunge', name: 'Walking Lunge', muscleGroup: 'Legs', equipment: 'Dumbbells', level: 'intermediate', type: 'gym', description: 'Functional movement for leg strength and balance.', instructions: ['Hold dumbbells at sides', 'Step forward into lunge', 'Lower until back knee near floor', 'Drive up and step forward with other leg'], commonMistakes: ['Short steps', 'Knee going past toes', 'Leaning forward'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'], sets: 3, reps: '12 each', restSeconds: 75 },
  { id: 'goblet-squat', name: 'Goblet Squat', muscleGroup: 'Legs', equipment: 'Dumbbell', level: 'beginner', type: 'gym', description: 'Beginner-friendly squat for learning proper form.', instructions: ['Hold dumbbell at chest', 'Feet shoulder-width apart', 'Squat to depth keeping chest up', 'Drive up through heels'], commonMistakes: ['Leaning forward', 'Knees caving', 'Not deep enough'], musclesWorked: ['Quadriceps', 'Glutes', 'Core'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'smith-squat', name: 'Smith Machine Squat', muscleGroup: 'Legs', equipment: 'Smith Machine', level: 'beginner', type: 'gym', description: 'Guided squatting for safe progressive overload.', instructions: ['Position bar on upper back', 'Feet slightly forward of bar', 'Squat to parallel', 'Press up to lockout'], commonMistakes: ['Feet too far back', 'Not enough depth', 'Relying on machine'], musclesWorked: ['Quadriceps', 'Glutes'], sets: 4, reps: '10-12', restSeconds: 90 },
  { id: 'seated-calf-raise', name: 'Seated Calf Raise', muscleGroup: 'Legs', equipment: 'Seated Calf Machine', level: 'beginner', type: 'gym', description: 'Targets the soleus for complete calf development.', instructions: ['Sit with pads on knees', 'Press up through balls of feet', 'Full stretch at bottom', 'Squeeze at top'], commonMistakes: ['Bouncing', 'Not enough ROM', 'Going too fast'], musclesWorked: ['Soleus', 'Gastrocnemius'], sets: 4, reps: '15-20', restSeconds: 45 },
  { id: 'sumo-deadlift', name: 'Sumo Deadlift', muscleGroup: 'Legs', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Wide stance deadlift targeting inner thighs and glutes.', instructions: ['Wide stance, toes pointed out', 'Grip bar between legs', 'Drive through heels, push knees out', 'Lock out at top'], commonMistakes: ['Knees caving', 'Rounding back', 'Hips shooting up first'], musclesWorked: ['Glutes', 'Inner Thighs', 'Hamstrings', 'Quads'], sets: 4, reps: '6-8', restSeconds: 120 },
  { id: 'step-up', name: 'Step-Up', muscleGroup: 'Legs', equipment: 'Dumbbells, Box', level: 'beginner', type: 'gym', description: 'Functional unilateral exercise for legs and glutes.', instructions: ['Hold dumbbells at sides', 'Step up onto box with one foot', 'Drive up to full stand', 'Step down with control'], commonMistakes: ['Pushing off back foot', 'Box too high', 'Leaning forward'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'], sets: 3, reps: '10-12 each', restSeconds: 60 },
  { id: 'good-morning', name: 'Good Morning', muscleGroup: 'Legs', equipment: 'Barbell', level: 'intermediate', type: 'gym', description: 'Strengthens posterior chain with hip hinge.', instructions: ['Bar on upper back', 'Hinge at hips pushing back', 'Keep slight knee bend', 'Return to standing'], commonMistakes: ['Rounding back', 'Going too heavy', 'Bending knees too much'], musclesWorked: ['Hamstrings', 'Erector Spinae', 'Glutes'], sets: 3, reps: '10-12', restSeconds: 75 },

  // ===== ABS (10 exercises) =====
  { id: 'cable-crunch', name: 'Cable Crunch', muscleGroup: 'Abs', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Weighted ab exercise for thick, defined abs.', instructions: ['Kneel in front of cable machine', 'Hold rope behind head', 'Crunch down bringing elbows to knees', 'Control the return'], commonMistakes: ['Hip flexion instead of spinal flexion', 'Too much weight', 'Not controlling negative'], musclesWorked: ['Rectus Abdominis'], sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'hanging-leg-raise', name: 'Hanging Leg Raise', muscleGroup: 'Abs', equipment: 'Pull-up Bar', level: 'intermediate', type: 'gym', description: 'Advanced lower ab exercise.', instructions: ['Hang from pull-up bar', 'Raise legs to parallel or higher', 'Control the lowering phase', 'Avoid swinging'], commonMistakes: ['Using momentum', 'Not raising high enough', 'Swinging'], musclesWorked: ['Lower Abs', 'Hip Flexors'], sets: 3, reps: '10-15', restSeconds: 60 },
  { id: 'ab-wheel', name: 'Ab Wheel Rollout', muscleGroup: 'Abs', equipment: 'Ab Wheel', level: 'intermediate', type: 'gym', description: 'Full core engagement with anti-extension challenge.', instructions: ['Kneel with ab wheel in front', 'Roll forward extending body', 'Go as far as you can control', 'Roll back using abs'], commonMistakes: ['Arching lower back', 'Going too far', 'Using hip flexors'], musclesWorked: ['Rectus Abdominis', 'Obliques', 'Core'], sets: 3, reps: '8-12', restSeconds: 60 },
  { id: 'plank', name: 'Plank', muscleGroup: 'Abs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Isometric core endurance exercise.', instructions: ['Forearms on floor, body straight', 'Engage core and glutes', 'Hold position without sagging', 'Breathe normally'], commonMistakes: ['Hips too high', 'Hips sagging', 'Not engaging core'], musclesWorked: ['Core', 'Rectus Abdominis', 'Obliques'], sets: 3, reps: '30-60s hold', restSeconds: 45 },
  { id: 'russian-twist', name: 'Russian Twist', muscleGroup: 'Abs', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Rotational core exercise for obliques.', instructions: ['Sit with knees bent, feet elevated', 'Lean back slightly', 'Rotate torso side to side', 'Touch floor on each side'], commonMistakes: ['Not rotating enough', 'Losing balance', 'Moving too fast'], musclesWorked: ['Obliques', 'Rectus Abdominis', 'Hip Flexors'], sets: 3, reps: '20 total', restSeconds: 45 },
  { id: 'bicycle-crunch', name: 'Bicycle Crunch', muscleGroup: 'Abs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Dynamic crunch targeting obliques and rectus abdominis.', instructions: ['Lie on back, hands behind head', 'Bring opposite elbow to knee', 'Extend other leg straight', 'Alternate sides'], commonMistakes: ['Pulling on neck', 'Not fully extending leg', 'Moving too fast'], musclesWorked: ['Obliques', 'Rectus Abdominis'], sets: 3, reps: '20 total', restSeconds: 45 },
  { id: 'mountain-climber', name: 'Mountain Climber', muscleGroup: 'Abs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Dynamic core exercise with cardio benefit.', instructions: ['Start in push-up position', 'Drive knee toward chest', 'Alternate legs rapidly', 'Keep hips level'], commonMistakes: ['Hips bouncing up', 'Not driving knees far enough', 'Losing core tension'], musclesWorked: ['Core', 'Hip Flexors', 'Shoulders'], sets: 3, reps: '30 total', restSeconds: 45 },
  { id: 'toe-touch', name: 'Toe Touch', muscleGroup: 'Abs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Upper ab focused crunch variation.', instructions: ['Lie on back with legs vertical', 'Reach hands toward toes', 'Crunch upper body off floor', 'Lower with control'], commonMistakes: ['Using momentum', 'Not lifting shoulders', 'Bending legs'], musclesWorked: ['Upper Abs'], sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'dead-bug', name: 'Dead Bug', muscleGroup: 'Abs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Anti-extension core exercise for stability.', instructions: ['Lie on back, arms and legs up', 'Extend opposite arm and leg', 'Keep lower back pressed to floor', 'Return and alternate'], commonMistakes: ['Arching lower back', 'Moving too fast', 'Not coordinating limbs'], musclesWorked: ['Core', 'Rectus Abdominis'], sets: 3, reps: '12 each', restSeconds: 45 },
  { id: 'side-plank', name: 'Side Plank', muscleGroup: 'Abs', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Lateral core stability exercise.', instructions: ['Lie on side, forearm on floor', 'Lift hips off floor', 'Body in straight line', 'Hold position'], commonMistakes: ['Hips dropping', 'Rolling forward or back', 'Not engaging obliques'], musclesWorked: ['Obliques', 'Core'], sets: 3, reps: '30s each side', restSeconds: 30 },

  // ===== GLUTES (8 exercises) =====
  { id: 'hip-thrust', name: 'Hip Thrust', muscleGroup: 'Glutes', equipment: 'Barbell, Bench', level: 'intermediate', type: 'gym', description: 'The #1 glute builder. Maximum glute activation.', instructions: ['Upper back on bench', 'Bar across hips with pad', 'Drive hips up to full extension', 'Squeeze glutes at top'], commonMistakes: ['Hyperextending lower back', 'Not full hip extension', 'Feet too far forward'], musclesWorked: ['Gluteus Maximus', 'Hamstrings'], sets: 4, reps: '10-12', restSeconds: 75 },
  { id: 'bulgarian-split-squat', name: 'Bulgarian Split Squat', muscleGroup: 'Glutes', equipment: 'Dumbbells, Bench', level: 'intermediate', type: 'gym', description: 'Unilateral exercise for glutes and imbalance correction.', instructions: ['Rear foot on bench', 'Lower until front thigh parallel', 'Drive through front heel', 'Keep torso upright'], commonMistakes: ['Front knee past toe', 'Leaning too far forward', 'Back foot too far from bench'], musclesWorked: ['Glutes', 'Quadriceps', 'Hamstrings'], sets: 3, reps: '10-12 each', restSeconds: 75 },
  { id: 'cable-kickback', name: 'Cable Kickback', muscleGroup: 'Glutes', equipment: 'Cable Machine', level: 'beginner', type: 'gym', description: 'Isolation for glute activation and shaping.', instructions: ['Attach ankle strap to low cable', 'Kick leg straight back', 'Squeeze glute at top', 'Control return'], commonMistakes: ['Arching lower back', 'Using momentum', 'Not squeezing at top'], musclesWorked: ['Gluteus Maximus'], sets: 3, reps: '12-15 each', restSeconds: 45 },
  { id: 'sumo-squat', name: 'Sumo Squat', muscleGroup: 'Glutes', equipment: 'Dumbbell', level: 'beginner', type: 'gym', description: 'Wide stance squat for inner thighs and glutes.', instructions: ['Wide stance, toes pointed out', 'Hold dumbbell in front', 'Squat down keeping chest up', 'Drive up through heels'], commonMistakes: ['Knees caving', 'Leaning forward', 'Not deep enough'], musclesWorked: ['Glutes', 'Inner Thighs', 'Quadriceps'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'glute-bridge', name: 'Glute Bridge', muscleGroup: 'Glutes', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Bodyweight glute activation exercise.', instructions: ['Lie on back, knees bent', 'Drive hips up squeezing glutes', 'Hold at top briefly', 'Lower with control'], commonMistakes: ['Not squeezing at top', 'Using lower back', 'Not driving through heels'], musclesWorked: ['Gluteus Maximus', 'Hamstrings'], sets: 3, reps: '15-20', restSeconds: 45 },
  { id: 'single-leg-hip-thrust', name: 'Single-Leg Hip Thrust', muscleGroup: 'Glutes', equipment: 'Bench', level: 'advanced', type: 'gym', description: 'Unilateral hip thrust for imbalance correction.', instructions: ['Upper back on bench, one foot on floor', 'Extend other leg straight', 'Drive hips up with single leg', 'Squeeze glute at top'], commonMistakes: ['Rotating hips', 'Not full extension', 'Using lower back'], musclesWorked: ['Gluteus Maximus', 'Hamstrings', 'Core'], sets: 3, reps: '10-12 each', restSeconds: 60 },
  { id: 'fire-hydrant', name: 'Fire Hydrant', muscleGroup: 'Glutes', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Targets gluteus medius for hip stability.', instructions: ['On all fours', 'Lift knee out to side', 'Keep 90-degree knee angle', 'Lower with control'], commonMistakes: ['Rotating hips', 'Not lifting high enough', 'Rushing reps'], musclesWorked: ['Gluteus Medius', 'Gluteus Maximus'], sets: 3, reps: '15 each', restSeconds: 30 },
  { id: 'donkey-kick', name: 'Donkey Kick', muscleGroup: 'Glutes', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Isolates glutes with knee bent kick back.', instructions: ['On all fours', 'Kick one leg back and up', 'Squeeze glute at top', 'Lower with control'], commonMistakes: ['Arching back', 'Using momentum', 'Not full contraction'], musclesWorked: ['Gluteus Maximus'], sets: 3, reps: '15 each', restSeconds: 30 },

  // ===== CALISTHENICS - ADVANCED =====
  { id: 'pull-up', name: 'Pull-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'intermediate', type: 'calisthenics', description: 'The ultimate back builder using bodyweight.', instructions: ['Grip bar slightly wider than shoulders', 'Pull until chin clears bar', 'Lower with full control', 'Start from dead hang'], commonMistakes: ['Kipping or swinging', 'Not going to full hang', 'Chin not clearing bar'], musclesWorked: ['Latissimus Dorsi', 'Biceps', 'Rear Deltoids', 'Core'], sets: 4, reps: '8-12', restSeconds: 90 },
  { id: 'chin-up', name: 'Chin-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'beginner', type: 'calisthenics', description: 'Supinated grip pull-up with more bicep involvement.', instructions: ['Grip bar with palms facing you', 'Pull until chin clears bar', 'Lower to full hang', 'Control the descent'], commonMistakes: ['Not full ROM', 'Kipping', 'Grip too wide'], musclesWorked: ['Biceps', 'Latissimus Dorsi', 'Core'], sets: 3, reps: '8-12', restSeconds: 75 },
  { id: 'handstand-push-up', name: 'Handstand Push-Up', muscleGroup: 'Shoulders', equipment: 'Wall', level: 'advanced', type: 'calisthenics', description: 'Advanced shoulder exercise requiring strength and balance.', instructions: ['Kick up to handstand against wall', 'Lower head toward floor', 'Press back up to full extension', 'Keep core tight'], commonMistakes: ['Not going deep enough', 'Arching back', 'Kicking up unsafely'], musclesWorked: ['Deltoids', 'Triceps', 'Upper Chest', 'Core'], sets: 3, reps: '5-8', restSeconds: 120 },
  { id: 'muscle-up', name: 'Muscle-Up', muscleGroup: 'Back', equipment: 'Pull-up Bar', level: 'advanced', type: 'calisthenics', description: 'The pinnacle of upper body calisthenics.', instructions: ['Start from dead hang', 'Explosive pull above the bar', 'Transition to dip position', 'Press to lockout above bar'], commonMistakes: ['Not enough explosive pull', 'Chicken winging', 'Kipping too much'], musclesWorked: ['Lats', 'Chest', 'Triceps', 'Biceps', 'Core'], sets: 3, reps: '3-5', restSeconds: 120 },
  { id: 'l-sit', name: 'L-Sit', muscleGroup: 'Abs', equipment: 'Parallel Bars or Floor', level: 'advanced', type: 'calisthenics', description: 'Isometric core exercise building incredible ab strength.', instructions: ['Support body on hands', 'Extend legs straight in front', 'Hold position with legs parallel to floor', 'Keep shoulders depressed'], commonMistakes: ['Bending knees', 'Shoulders rising', 'Not holding long enough'], musclesWorked: ['Abs', 'Hip Flexors', 'Triceps', 'Shoulders'], sets: 3, reps: '15-30s hold', restSeconds: 90 },
  { id: 'pistol-squat', name: 'Pistol Squat', muscleGroup: 'Legs', equipment: 'None', level: 'advanced', type: 'calisthenics', description: 'Single-leg squat requiring extreme strength and balance.', instructions: ['Stand on one leg', 'Extend other leg forward', 'Squat down to full depth', 'Stand back up without assistance'], commonMistakes: ['Heel lifting', 'Losing balance', 'Not going deep enough'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings', 'Core'], sets: 3, reps: '5-8 each', restSeconds: 90 },
  { id: 'dragon-flag', name: 'Dragon Flag', muscleGroup: 'Abs', equipment: 'Bench', level: 'advanced', type: 'calisthenics', description: "Bruce Lee's signature ab exercise. Builds steel-like core.", instructions: ['Lie on bench, grip behind head', 'Raise entire body to vertical', 'Lower body keeping rigid', 'Only shoulder blades touch bench'], commonMistakes: ['Bending at hips', 'Going too fast', 'Not enough control'], musclesWorked: ['Entire Core', 'Hip Flexors', 'Lower Back'], sets: 3, reps: '5-8', restSeconds: 90 },
  { id: 'planche-lean', name: 'Planche Lean', muscleGroup: 'Shoulders', equipment: 'Floor', level: 'advanced', type: 'calisthenics', description: 'Builds shoulder and wrist strength for planche.', instructions: ['Start in push-up position', 'Lean forward shifting weight to hands', 'Keep arms straight', 'Hold the lean position'], commonMistakes: ['Bending arms', 'Not leaning far enough', 'Hips too high'], musclesWorked: ['Anterior Deltoids', 'Core', 'Wrist Flexors'], sets: 3, reps: '15-20s hold', restSeconds: 60 },
  { id: 'australian-pull-up', name: 'Australian Pull-Up', muscleGroup: 'Back', equipment: 'Low Bar', level: 'beginner', type: 'calisthenics', description: 'Horizontal pull. Great progression toward full pull-ups.', instructions: ['Hang under a low bar', 'Pull chest to bar', 'Keep body in straight line', 'Lower with control'], commonMistakes: ['Hips sagging', 'Not pulling to chest', 'Using momentum'], musclesWorked: ['Lats', 'Rhomboids', 'Biceps', 'Rear Deltoids'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'pike-push-up', name: 'Pike Push-Up', muscleGroup: 'Shoulders', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Progression toward handstand push-ups.', instructions: ['Start in pike position, hips high', 'Lower head toward floor', 'Press back up', 'Keep legs straight'], commonMistakes: ['Not enough hip angle', 'Bending legs', 'Moving hips during reps'], musclesWorked: ['Deltoids', 'Triceps', 'Upper Chest'], sets: 3, reps: '8-12', restSeconds: 60 },
  { id: 'bodyweight-squat', name: 'Bodyweight Squat', muscleGroup: 'Legs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Fundamental lower body exercise.', instructions: ['Stand with feet shoulder-width', 'Squat down keeping chest up', 'Go to parallel or below', 'Drive up through heels'], commonMistakes: ['Knees caving', 'Not deep enough', 'Leaning forward'], musclesWorked: ['Quadriceps', 'Glutes', 'Hamstrings'], sets: 3, reps: '20-30', restSeconds: 45 },
  { id: 'burpee', name: 'Burpee', muscleGroup: 'Full Body', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Full body conditioning exercise.', instructions: ['Stand, then drop to push-up', 'Perform push-up', 'Jump feet forward', 'Jump up with arms overhead'], commonMistakes: ['Skipping push-up', 'Lazy jumps', 'Poor form'], musclesWorked: ['Full Body', 'Core', 'Legs', 'Chest'], sets: 3, reps: '10-15', restSeconds: 60 },
  { id: 'jump-squat', name: 'Jump Squat', muscleGroup: 'Legs', equipment: 'None', level: 'intermediate', type: 'calisthenics', description: 'Plyometric squat for explosive power.', instructions: ['Squat down to parallel', 'Explode upward jumping', 'Land softly on balls of feet', 'Immediately descend into next rep'], commonMistakes: ['Landing hard', 'Shallow squat', 'Knees caving'], musclesWorked: ['Quadriceps', 'Glutes', 'Calves'], sets: 3, reps: '12-15', restSeconds: 60 },
  { id: 'wall-sit', name: 'Wall Sit', muscleGroup: 'Legs', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Isometric quad endurance exercise.', instructions: ['Back flat against wall', 'Slide down to 90-degree knee angle', 'Hold position', 'Keep back pressed to wall'], commonMistakes: ['Not deep enough', 'Leaning forward', 'Hands on thighs'], musclesWorked: ['Quadriceps', 'Glutes'], sets: 3, reps: '30-60s hold', restSeconds: 45 },
  { id: 'bear-crawl', name: 'Bear Crawl', muscleGroup: 'Full Body', equipment: 'None', level: 'beginner', type: 'calisthenics', description: 'Functional movement for core and coordination.', instructions: ['On all fours, knees hovering', 'Move opposite hand and foot forward', 'Keep hips low and stable', 'Alternate sides'], commonMistakes: ['Hips too high', 'Not coordinating limbs', 'Moving too fast'], musclesWorked: ['Core', 'Shoulders', 'Quadriceps'], sets: 3, reps: '30s', restSeconds: 45 },
  ...videoExercises,
];

export const getExercisesByCategory = (category: 'gym' | 'bodyweight' | 'stretching') =>
  exercises.filter(e => (e.category ?? (e.type === 'gym' ? 'gym' : 'bodyweight')) === category);
export const exercisesWithVideo = () => exercises.filter(e => !!e.videoUrl);

export const getExercisesByMuscleGroup = (group: string) => exercises.filter(e => e.muscleGroup === group);
export const getExercisesByType = (type: 'gym' | 'calisthenics') => exercises.filter(e => e.type === type);
export const getExerciseById = (id: string) => exercises.find(e => e.id === id);
