import { Exercise } from './types';

import lyingPunches from '@/assets/videos/lying-punches.mp4.asset.json';
import lyingBackRaise from '@/assets/videos/lying-alternate-back-raise.mp4.asset.json';
import woodchoppers from '@/assets/videos/double-woodchoppers.mp4.asset.json';
import russianTwistChair from '@/assets/videos/sitting-russian-twist-on-a-chair.mp4.asset.json';
import armCircleChair from '@/assets/videos/seated-underhand-arm-circle-on-a-chair.mp4.asset.json';
import legRaiseChair from '@/assets/videos/seated-extended-leg-raise-on-a-chair.mp4.asset.json';
import hipKneeRaise from '@/assets/videos/lying-hip-knee-raise.mp4.asset.json';
import kneeExtensionChair from '@/assets/videos/seated-alternate-knee-extension-on-chair.mp4.asset.json';
import hipFlexorKneeling from '@/assets/videos/kneeling-hip-flexor-frontal.mp4.asset.json';
import standToSquat from '@/assets/videos/stand-to-squat-v2.mp4.asset.json';
import airBikeChair from '@/assets/videos/seated-air-bike-chair-v2.mp4.asset.json';
import scapularAdduction from '@/assets/videos/sitting-scapular-adduction-v2.mp4.asset.json';
import floorSlide from '@/assets/videos/lying-floor-slide-v2.mp4.asset.json';
import lyingLegCurl from '@/assets/videos/bodyweight-lying-leg-curl-v2.mp4.asset.json';
import overheadSitUp from '@/assets/videos/arms-overhead-full-situp-v2.mp4.asset.json';
import deepSquatHead from '@/assets/videos/deep-squat-head-to-floor-v2.mp4.asset.json';
import squatMobilitySideBend from '@/assets/videos/squat-mobility-side-bend.mp4.asset.json';

/** Exercises that ship with an animated demonstration video. */
export const videoExercises: Exercise[] = [
  {
    id: 'lying-punches',
    name: 'Lying Punches',
    muscleGroup: 'Chest',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: lyingPunches.url,
    description: 'Lying chest activation with alternating punches. Great warm-up and endurance work.',
    instructions: ['Lie on your back with knees bent and feet flat', 'Lift shoulders slightly off the floor', 'Punch straight up alternating arms', 'Keep the core braced and breathe steadily'],
    commonMistakes: ['Locking the elbows hard', 'Holding the breath', 'Letting the lower back arch'],
    musclesWorked: ['Pectoralis Major', 'Anterior Deltoids', 'Core'],
    sets: 3, reps: '30-40s', restSeconds: 45,
    translations: {
      pt: { name: 'Socos Deitado', description: 'Ativação de peito deitado com socos alternados. Ótimo para aquecimento e resistência.',
        instructions: ['Deite de costas com joelhos dobrados e pés apoiados', 'Eleve levemente os ombros do chão', 'Dê socos para cima alternando os braços', 'Mantenha o abdômen contraído e respire de forma constante'],
        commonMistakes: ['Travar o cotovelo com força', 'Prender a respiração', 'Arquear a lombar'],
        musclesWorked: ['Peitoral Maior', 'Deltoide Anterior', 'Core'] },
      es: { name: 'Golpes Tumbado', description: 'Activación de pecho tumbado con golpes alternos. Ideal para calentar y ganar resistencia.',
        instructions: ['Túmbate boca arriba con rodillas flexionadas', 'Eleva ligeramente los hombros del suelo', 'Lanza golpes hacia arriba alternando brazos', 'Mantén el core activo y respira'],
        commonMistakes: ['Bloquear los codos', 'Aguantar la respiración', 'Arquear la zona lumbar'],
        musclesWorked: ['Pectoral Mayor', 'Deltoides Anterior', 'Core'] },
    },
  },
  {
    id: 'lying-alternate-back-raise',
    name: 'Lying Alternate Back Raise',
    muscleGroup: 'Back',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: lyingBackRaise.url,
    description: 'Prone superman variation that strengthens the lower back and posterior chain.',
    instructions: ['Lie face down with arms extended overhead', 'Raise the right arm and left leg together', 'Hold for a second at the top', 'Lower and alternate sides'],
    commonMistakes: ['Jerking the movement', 'Lifting the head too high', 'Rushing without a pause'],
    musclesWorked: ['Erector Spinae', 'Glutes', 'Posterior Deltoids'],
    sets: 3, reps: '12-16', restSeconds: 45,
    translations: {
      pt: { name: 'Extensão Lombar Alternada', description: 'Variação do superman que fortalece a lombar e a cadeia posterior.',
        instructions: ['Deite de barriga para baixo com os braços à frente', 'Eleve o braço direito e a perna esquerda juntos', 'Segure por um segundo no topo', 'Desça e alterne os lados'],
        commonMistakes: ['Fazer o movimento com impulso', 'Levantar demais a cabeça', 'Não pausar no topo'],
        musclesWorked: ['Eretores da Espinha', 'Glúteos', 'Deltoide Posterior'] },
      es: { name: 'Extensión Lumbar Alterna', description: 'Variación del superman que fortalece la lumbar y la cadena posterior.',
        instructions: ['Túmbate boca abajo con los brazos extendidos', 'Eleva brazo derecho y pierna izquierda a la vez', 'Mantén un segundo arriba', 'Baja y alterna lados'],
        commonMistakes: ['Usar impulso', 'Levantar mucho la cabeza', 'No pausar arriba'],
        musclesWorked: ['Erectores Espinales', 'Glúteos', 'Deltoides Posterior'] },
    },
  },
  {
    id: 'double-woodchoppers',
    name: 'Double Woodchoppers',
    muscleGroup: 'Full Body',
    equipment: 'None',
    level: 'intermediate',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: woodchoppers.url,
    description: 'Explosive full-body chopping movement that raises the heart rate and works the obliques.',
    instructions: ['Stand with feet shoulder-width apart', 'Raise both arms overhead', 'Chop down diagonally while bending the knees', 'Return explosively and alternate sides'],
    commonMistakes: ['Rounding the back on the chop', 'Only moving the arms', 'Locking the knees'],
    musclesWorked: ['Obliques', 'Core', 'Shoulders', 'Legs'],
    sets: 3, reps: '20-30s', restSeconds: 45,
    translations: {
      pt: { name: 'Lenhador Duplo', description: 'Movimento explosivo de corpo inteiro que acelera o coração e trabalha os oblíquos.',
        instructions: ['Fique em pé com os pés na largura dos ombros', 'Eleve os dois braços acima da cabeça', 'Desça em diagonal dobrando os joelhos', 'Volte explosivamente e alterne os lados'],
        commonMistakes: ['Arredondar as costas na descida', 'Mover só os braços', 'Travar os joelhos'],
        musclesWorked: ['Oblíquos', 'Core', 'Ombros', 'Pernas'] },
      es: { name: 'Leñador Doble', description: 'Movimiento explosivo de cuerpo completo que eleva el pulso y trabaja los oblicuos.',
        instructions: ['De pie con pies al ancho de hombros', 'Eleva ambos brazos por encima de la cabeza', 'Baja en diagonal flexionando rodillas', 'Vuelve explosivo y alterna lados'],
        commonMistakes: ['Redondear la espalda', 'Mover solo los brazos', 'Bloquear las rodillas'],
        musclesWorked: ['Oblicuos', 'Core', 'Hombros', 'Piernas'] },
    },
  },
  {
    id: 'sitting-russian-twist-chair',
    name: 'Seated Russian Twist on a Chair',
    muscleGroup: 'Abs',
    equipment: 'Chair',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: russianTwistChair.url,
    description: 'Seated rotational core exercise, perfect for training at home or at the office.',
    instructions: ['Sit on the edge of a chair with a tall spine', 'Lean back slightly and lift the chest', 'Rotate the torso from side to side', 'Control the movement, do not swing'],
    commonMistakes: ['Rotating only the arms', 'Slouching the back', 'Moving too fast'],
    musclesWorked: ['Obliques', 'Rectus Abdominis', 'Core'],
    sets: 3, reps: '16-24', restSeconds: 40,
    translations: {
      pt: { name: 'Torção Russa Sentado na Cadeira', description: 'Exercício de core rotacional sentado, ideal para treinar em casa ou no trabalho.',
        instructions: ['Sente na ponta da cadeira com a coluna alongada', 'Incline levemente para trás e abra o peito', 'Gire o tronco de um lado para o outro', 'Controle o movimento, sem balançar'],
        commonMistakes: ['Girar só os braços', 'Curvar as costas', 'Fazer rápido demais'],
        musclesWorked: ['Oblíquos', 'Reto Abdominal', 'Core'] },
      es: { name: 'Giro Ruso Sentado en Silla', description: 'Ejercicio de core rotacional sentado, ideal para casa u oficina.',
        instructions: ['Siéntate al borde de la silla con la espalda recta', 'Inclínate ligeramente atrás', 'Gira el torso de lado a lado', 'Controla el movimiento'],
        commonMistakes: ['Girar solo los brazos', 'Encorvar la espalda', 'Ir demasiado rápido'],
        musclesWorked: ['Oblicuos', 'Recto Abdominal', 'Core'] },
    },
  },
  {
    id: 'seated-arm-circle-chair',
    name: 'Seated Underhand Arm Circle',
    muscleGroup: 'Shoulders',
    equipment: 'Chair',
    level: 'beginner',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: armCircleChair.url,
    description: 'Shoulder mobility drill with supinated arm circles. Ideal warm-up or desk break.',
    instructions: ['Sit tall with feet flat on the floor', 'Open both arms to the sides, palms facing up', 'Draw slow circles with the arms', 'Reverse the direction halfway through'],
    commonMistakes: ['Shrugging the shoulders', 'Circles too large and fast', 'Leaning the torso'],
    musclesWorked: ['Deltoids', 'Rotator Cuff', 'Upper Back'],
    sets: 2, reps: '30-45s', restSeconds: 30,
    translations: {
      pt: { name: 'Círculos de Braço Sentado', description: 'Mobilidade de ombro com círculos de braço supinados. Ótimo aquecimento ou pausa do trabalho.',
        instructions: ['Sente com a coluna ereta e pés no chão', 'Abra os braços para os lados com as palmas para cima', 'Faça círculos lentos com os braços', 'Inverta o sentido na metade do tempo'],
        commonMistakes: ['Levantar os ombros', 'Círculos grandes e rápidos demais', 'Inclinar o tronco'],
        musclesWorked: ['Deltoides', 'Manguito Rotador', 'Costas Superiores'] },
      es: { name: 'Círculos de Brazo Sentado', description: 'Movilidad de hombro con círculos supinados. Ideal para calentar o pausas activas.',
        instructions: ['Siéntate erguido con los pies en el suelo', 'Abre los brazos con las palmas hacia arriba', 'Haz círculos lentos', 'Invierte el sentido a la mitad'],
        commonMistakes: ['Encoger los hombros', 'Círculos muy rápidos', 'Inclinar el torso'],
        musclesWorked: ['Deltoides', 'Manguito Rotador', 'Espalda Alta'] },
    },
  },
  {
    id: 'seated-leg-raise-chair',
    name: 'Seated Extended Leg Raise',
    muscleGroup: 'Legs',
    equipment: 'Chair',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: legRaiseChair.url,
    description: 'Seated hip flexor and quad activation with extended legs.',
    instructions: ['Sit on the edge of the chair holding the sides', 'Extend one leg straight in front', 'Raise it as high as comfortable', 'Lower slowly and switch legs'],
    commonMistakes: ['Leaning back excessively', 'Bending the knee', 'Dropping the leg without control'],
    musclesWorked: ['Hip Flexors', 'Quadriceps', 'Core'],
    sets: 3, reps: '12-15', restSeconds: 40,
    translations: {
      pt: { name: 'Elevação de Perna Estendida Sentado', description: 'Ativação de flexores do quadril e quadríceps sentado com a perna estendida.',
        instructions: ['Sente na ponta da cadeira segurando as laterais', 'Estenda uma perna à frente', 'Eleve o máximo que conseguir com conforto', 'Desça devagar e troque de perna'],
        commonMistakes: ['Inclinar demais para trás', 'Dobrar o joelho', 'Soltar a perna sem controle'],
        musclesWorked: ['Flexores do Quadril', 'Quadríceps', 'Core'] },
      es: { name: 'Elevación de Pierna Extendida Sentado', description: 'Activación de flexores de cadera y cuádriceps en silla.',
        instructions: ['Siéntate al borde sujetando los lados', 'Extiende una pierna al frente', 'Elévala lo más cómodo posible', 'Baja despacio y cambia'],
        commonMistakes: ['Inclinarse mucho atrás', 'Doblar la rodilla', 'Soltar la pierna sin control'],
        musclesWorked: ['Flexores de Cadera', 'Cuádriceps', 'Core'] },
    },
  },
  {
    id: 'lying-hip-knee-raise',
    name: 'Lying Hip & Knee Raise',
    muscleGroup: 'Abs',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: hipKneeRaise.url,
    description: 'Lower ab exercise lifting the hips with the knees bent.',
    instructions: ['Lie on your back with arms at your sides', 'Bring the knees over the hips', 'Lift the hips off the floor using the abs', 'Lower slowly without swinging'],
    commonMistakes: ['Using momentum from the legs', 'Pushing with the hands', 'Lifting the neck'],
    musclesWorked: ['Lower Abs', 'Rectus Abdominis', 'Hip Flexors'],
    sets: 3, reps: '12-18', restSeconds: 45,
    translations: {
      pt: { name: 'Elevação de Quadril e Joelhos', description: 'Exercício de abdômen inferior elevando o quadril com joelhos dobrados.',
        instructions: ['Deite de costas com os braços ao lado do corpo', 'Traga os joelhos acima do quadril', 'Eleve o quadril do chão usando o abdômen', 'Desça devagar sem embalo'],
        commonMistakes: ['Usar impulso das pernas', 'Empurrar com as mãos', 'Forçar o pescoço'],
        musclesWorked: ['Abdômen Inferior', 'Reto Abdominal', 'Flexores do Quadril'] },
      es: { name: 'Elevación de Cadera y Rodillas', description: 'Ejercicio de abdomen inferior elevando la cadera con rodillas flexionadas.',
        instructions: ['Túmbate con los brazos a los lados', 'Lleva las rodillas sobre la cadera', 'Eleva la cadera usando el abdomen', 'Baja despacio sin impulso'],
        commonMistakes: ['Usar impulso', 'Empujar con las manos', 'Forzar el cuello'],
        musclesWorked: ['Abdomen Inferior', 'Recto Abdominal', 'Flexores de Cadera'] },
    },
  },
  {
    id: 'seated-knee-extension-chair',
    name: 'Seated Alternate Knee Extension',
    muscleGroup: 'Legs',
    equipment: 'Chair',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: kneeExtensionChair.url,
    description: 'Quadriceps isolation without equipment, alternating leg extensions on a chair.',
    instructions: ['Sit with the back supported and feet flat', 'Extend one knee until the leg is straight', 'Squeeze the quad at the top', 'Lower with control and alternate'],
    commonMistakes: ['Swinging the leg', 'Not fully extending', 'Sliding forward on the seat'],
    musclesWorked: ['Quadriceps', 'Hip Flexors'],
    sets: 3, reps: '15-20', restSeconds: 40,
    translations: {
      pt: { name: 'Extensão de Joelho Alternada Sentado', description: 'Isolamento de quadríceps sem equipamento, com extensões alternadas na cadeira.',
        instructions: ['Sente com as costas apoiadas e pés no chão', 'Estenda um joelho até a perna ficar reta', 'Contraia o quadríceps no topo', 'Desça com controle e alterne'],
        commonMistakes: ['Balançar a perna', 'Não estender por completo', 'Escorregar no assento'],
        musclesWorked: ['Quadríceps', 'Flexores do Quadril'] },
      es: { name: 'Extensión de Rodilla Alterna Sentado', description: 'Aislamiento de cuádriceps sin equipo, con extensiones alternas en silla.',
        instructions: ['Siéntate con la espalda apoyada', 'Extiende una rodilla hasta estirar la pierna', 'Aprieta el cuádriceps arriba', 'Baja controlado y alterna'],
        commonMistakes: ['Balancear la pierna', 'No extender del todo', 'Deslizarse en el asiento'],
        musclesWorked: ['Cuádriceps', 'Flexores de Cadera'] },
    },
  },
  {
    id: 'kneeling-hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    muscleGroup: 'Legs',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: hipFlexorKneeling.url,
    description: 'Classic kneeling stretch that opens the hip flexors and relieves lower back tension.',
    instructions: ['Kneel with one foot forward at 90 degrees', 'Tuck the pelvis slightly under', 'Push the hips forward until you feel the stretch', 'Hold and breathe, then switch sides'],
    commonMistakes: ['Arching the lower back', 'Front knee past the toes', 'Holding the breath'],
    musclesWorked: ['Hip Flexors', 'Quadriceps', 'Glutes'],
    sets: 2, reps: '30-45s', restSeconds: 20,
    translations: {
      pt: { name: 'Alongamento de Flexor do Quadril Ajoelhado', description: 'Alongamento clássico ajoelhado que abre os flexores do quadril e alivia a lombar.',
        instructions: ['Ajoelhe com um pé à frente a 90 graus', 'Encaixe levemente o quadril', 'Empurre o quadril para frente até sentir o alongamento', 'Segure respirando e troque de lado'],
        commonMistakes: ['Arquear a lombar', 'Joelho da frente passando do pé', 'Prender a respiração'],
        musclesWorked: ['Flexores do Quadril', 'Quadríceps', 'Glúteos'] },
      es: { name: 'Estiramiento de Flexor de Cadera Arrodillado', description: 'Estiramiento clásico que abre los flexores de cadera y alivia la lumbar.',
        instructions: ['Arrodíllate con un pie al frente a 90 grados', 'Retroversiona ligeramente la pelvis', 'Empuja la cadera al frente hasta sentir el estiramiento', 'Mantén respirando y cambia'],
        commonMistakes: ['Arquear la lumbar', 'Rodilla más allá del pie', 'Aguantar la respiración'],
        musclesWorked: ['Flexores de Cadera', 'Cuádriceps', 'Glúteos'] },
    },
  },
  {
    id: 'stand-to-squat',
    name: 'Stand to Squat',
    muscleGroup: 'Legs',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: standToSquat.url,
    description: 'Dynamic mobility drill moving from standing to a deep squat to open hips and ankles.',
    instructions: ['Stand with feet slightly wider than the hips', 'Hinge and lower into a deep squat', 'Keep the heels on the floor and chest tall', 'Stand back up slowly and repeat'],
    commonMistakes: ['Heels lifting off the floor', 'Rounding the lower back', 'Dropping down too fast'],
    musclesWorked: ['Hip Flexors', 'Glutes', 'Adductors', 'Calves'],
    sets: 2, reps: '10-12', restSeconds: 30,
    translations: {
      pt: { name: 'Agachamento Mobilidade em Pé', description: 'Mobilidade dinâmica de pé até o agachamento profundo para abrir quadril e tornozelos.',
        instructions: ['Fique em pé com os pés um pouco além da largura do quadril', 'Desça até o agachamento profundo', 'Mantenha os calcanhares no chão e o peito aberto', 'Suba devagar e repita'],
        commonMistakes: ['Levantar os calcanhares', 'Arredondar a lombar', 'Descer rápido demais'],
        musclesWorked: ['Flexores do Quadril', 'Glúteos', 'Adutores', 'Panturrilhas'] },
      es: { name: 'De Pie a Sentadilla', description: 'Movilidad dinámica de pie a sentadilla profunda para abrir cadera y tobillos.',
        instructions: ['De pie con pies algo más anchos que la cadera', 'Baja a una sentadilla profunda', 'Mantén talones en el suelo y pecho alto', 'Sube despacio y repite'],
        commonMistakes: ['Levantar los talones', 'Redondear la lumbar', 'Bajar muy rápido'],
        musclesWorked: ['Flexores de Cadera', 'Glúteos', 'Aductores', 'Gemelos'] },
    },
  },
  {
    id: 'seated-air-bike-chair',
    name: 'Seated Air Bike on a Chair',
    muscleGroup: 'Abs',
    equipment: 'Chair',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: airBikeChair.url,
    description: 'Seated pedalling motion that works the abs and hip flexors with zero impact.',
    instructions: ['Sit on the edge of the chair holding the sides', 'Lean back slightly and lift both feet', 'Pedal the legs as if riding a bike', 'Keep the abs braced the whole time'],
    commonMistakes: ['Letting the feet touch the floor', 'Slouching the back', 'Holding the breath'],
    musclesWorked: ['Rectus Abdominis', 'Hip Flexors', 'Obliques'],
    sets: 3, reps: '30-40s', restSeconds: 40,
    translations: {
      pt: { name: 'Bicicleta Sentado na Cadeira', description: 'Pedalada sentada que trabalha abdômen e flexores do quadril sem impacto.',
        instructions: ['Sente na ponta da cadeira segurando as laterais', 'Incline levemente para trás e eleve os pés', 'Pedale as pernas como em uma bicicleta', 'Mantenha o abdômen contraído'],
        commonMistakes: ['Deixar os pés tocarem o chão', 'Curvar as costas', 'Prender a respiração'],
        musclesWorked: ['Reto Abdominal', 'Flexores do Quadril', 'Oblíquos'] },
      es: { name: 'Bicicleta Sentado en Silla', description: 'Pedaleo sentado que trabaja abdomen y flexores de cadera sin impacto.',
        instructions: ['Siéntate al borde sujetando los lados', 'Inclínate atrás y eleva los pies', 'Pedalea como en bicicleta', 'Mantén el abdomen activo'],
        commonMistakes: ['Apoyar los pies', 'Encorvar la espalda', 'Aguantar la respiración'],
        musclesWorked: ['Recto Abdominal', 'Flexores de Cadera', 'Oblicuos'] },
    },
  },
  {
    id: 'sitting-scapular-adduction',
    name: 'Sitting Scapular Adduction',
    muscleGroup: 'Back',
    equipment: 'Chair',
    level: 'beginner',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: scapularAdduction.url,
    description: 'Posture drill that squeezes the shoulder blades together to fight desk slouching.',
    instructions: ['Sit tall with the chest open', 'Bend the elbows to 90 degrees at your sides', 'Pull the shoulder blades together', 'Hold two seconds and release slowly'],
    commonMistakes: ['Shrugging the shoulders up', 'Arching the lower back', 'Moving only the arms'],
    musclesWorked: ['Rhomboids', 'Middle Trapezius', 'Posterior Deltoids'],
    sets: 3, reps: '12-15', restSeconds: 30,
    translations: {
      pt: { name: 'Adução Escapular Sentado', description: 'Exercício postural que junta as escápulas para combater a postura curvada.',
        instructions: ['Sente ereto com o peito aberto', 'Dobre os cotovelos a 90 graus junto ao corpo', 'Junte as escápulas', 'Segure dois segundos e solte devagar'],
        commonMistakes: ['Levantar os ombros', 'Arquear a lombar', 'Mover só os braços'],
        musclesWorked: ['Romboides', 'Trapézio Médio', 'Deltoide Posterior'] },
      es: { name: 'Aducción Escapular Sentado', description: 'Ejercicio postural que junta las escápulas para combatir la postura encorvada.',
        instructions: ['Siéntate erguido con el pecho abierto', 'Flexiona los codos a 90 grados', 'Junta las escápulas', 'Mantén dos segundos y suelta'],
        commonMistakes: ['Encoger los hombros', 'Arquear la lumbar', 'Mover solo los brazos'],
        musclesWorked: ['Romboides', 'Trapecio Medio', 'Deltoides Posterior'] },
    },
  },
  {
    id: 'lying-floor-slide',
    name: 'Lying Floor Slide',
    muscleGroup: 'Back',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: floorSlide.url,
    description: 'Shoulder mobility drill sliding the arms along the floor to improve overhead range.',
    instructions: ['Lie on your back with knees bent', 'Place arms in a goalpost position on the floor', 'Slide the arms overhead keeping contact with the floor', 'Slide back down slowly'],
    commonMistakes: ['Lifting the arms off the floor', 'Arching the lower back', 'Rushing the slide'],
    musclesWorked: ['Rhomboids', 'Rotator Cuff', 'Middle Trapezius', 'Lats'],
    sets: 3, reps: '10-12', restSeconds: 30,
    translations: {
      pt: { name: 'Deslizamento de Braços no Chão', description: 'Mobilidade de ombro deslizando os braços no chão para ganhar amplitude acima da cabeça.',
        instructions: ['Deite de costas com os joelhos dobrados', 'Coloque os braços em formato de "gol" no chão', 'Deslize os braços acima da cabeça sem tirar do chão', 'Volte devagar à posição inicial'],
        commonMistakes: ['Tirar os braços do chão', 'Arquear a lombar', 'Fazer rápido demais'],
        musclesWorked: ['Romboides', 'Manguito Rotador', 'Trapézio Médio', 'Dorsais'] },
      es: { name: 'Deslizamiento de Brazos en el Suelo', description: 'Movilidad de hombro deslizando los brazos por el suelo para ganar rango.',
        instructions: ['Túmbate con las rodillas flexionadas', 'Coloca los brazos en posición de portería', 'Desliza los brazos por encima de la cabeza', 'Vuelve despacio'],
        commonMistakes: ['Despegar los brazos del suelo', 'Arquear la lumbar', 'Ir muy rápido'],
        musclesWorked: ['Romboides', 'Manguito Rotador', 'Trapecio Medio', 'Dorsales'] },
    },
  },
  {
    id: 'bodyweight-lying-leg-curl',
    name: 'Bodyweight Lying Leg Curl',
    muscleGroup: 'Legs',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: lyingLegCurl.url,
    description: 'Prone hamstring curl using only bodyweight, great for knee health and posterior chain.',
    instructions: ['Lie face down with legs extended', 'Curl the heels toward the glutes', 'Squeeze the hamstrings at the top', 'Lower slowly under control'],
    commonMistakes: ['Lifting the hips off the floor', 'Using momentum', 'Partial range of motion'],
    musclesWorked: ['Hamstrings', 'Glutes', 'Calves'],
    sets: 3, reps: '15-20', restSeconds: 45,
    translations: {
      pt: { name: 'Flexora Deitado Peso Corporal', description: 'Flexão de joelhos deitado só com o peso do corpo, ótima para a cadeia posterior.',
        instructions: ['Deite de barriga para baixo com as pernas estendidas', 'Leve os calcanhares em direção aos glúteos', 'Contraia os posteriores no topo', 'Desça devagar com controle'],
        commonMistakes: ['Levantar o quadril do chão', 'Usar impulso', 'Amplitude incompleta'],
        musclesWorked: ['Posteriores de Coxa', 'Glúteos', 'Panturrilhas'] },
      es: { name: 'Curl Femoral Tumbado sin Peso', description: 'Curl de isquiotibiales tumbado solo con el peso corporal.',
        instructions: ['Túmbate boca abajo con las piernas estiradas', 'Lleva los talones hacia los glúteos', 'Aprieta los isquios arriba', 'Baja despacio'],
        commonMistakes: ['Levantar la cadera', 'Usar impulso', 'Rango incompleto'],
        musclesWorked: ['Isquiotibiales', 'Glúteos', 'Gemelos'] },
    },
  },
  {
    id: 'arms-overhead-full-situp',
    name: 'Arms Overhead Full Sit-Up',
    muscleGroup: 'Abs',
    equipment: 'None',
    level: 'intermediate',
    type: 'calisthenics',
    category: 'bodyweight',
    videoUrl: overheadSitUp.url,
    description: 'Full range sit-up with the arms extended overhead for extra abdominal demand.',
    instructions: ['Lie on your back with arms extended overhead', 'Sweep the arms forward as you sit all the way up', 'Reach toward the toes at the top', 'Roll back down one vertebra at a time'],
    commonMistakes: ['Pulling with the neck', 'Throwing the arms for momentum', 'Feet lifting off the floor'],
    musclesWorked: ['Rectus Abdominis', 'Hip Flexors', 'Obliques'],
    sets: 3, reps: '12-20', restSeconds: 45,
    translations: {
      pt: { name: 'Abdominal Completo com Braços Estendidos', description: 'Abdominal de amplitude total com os braços acima da cabeça para exigir mais do abdômen.',
        instructions: ['Deite de costas com os braços estendidos acima da cabeça', 'Leve os braços à frente enquanto sobe por completo', 'Alcance os pés no topo', 'Volte desenrolando a coluna devagar'],
        commonMistakes: ['Puxar o pescoço', 'Jogar os braços para pegar impulso', 'Tirar os pés do chão'],
        musclesWorked: ['Reto Abdominal', 'Flexores do Quadril', 'Oblíquos'] },
      es: { name: 'Abdominal Completo con Brazos Extendidos', description: 'Abdominal de rango completo con los brazos por encima de la cabeza.',
        instructions: ['Túmbate con los brazos extendidos atrás', 'Lleva los brazos al frente al incorporarte', 'Alcanza los pies arriba', 'Baja vértebra a vértebra'],
        commonMistakes: ['Tirar del cuello', 'Usar impulso con los brazos', 'Despegar los pies'],
        musclesWorked: ['Recto Abdominal', 'Flexores de Cadera', 'Oblicuos'] },
    },
  },
  {
    id: 'deep-squat-head-to-floor',
    name: 'Deep Squat Head to Floor',
    muscleGroup: 'Legs',
    equipment: 'None',
    level: 'intermediate',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: deepSquatHead.url,
    description: 'Deep squat stretch bringing the head toward the floor to release hips, hamstrings and lower back.',
    instructions: ['Stand with feet wider than the hips', 'Squat down and place the hands on the floor', 'Lower the head toward the floor', 'Breathe deeply and hold the position'],
    commonMistakes: ['Forcing the neck down', 'Heels lifting', 'Bouncing in the stretch'],
    musclesWorked: ['Hamstrings', 'Glutes', 'Adductors', 'Erector Spinae'],
    sets: 2, reps: '30-45s', restSeconds: 20,
    translations: {
      pt: { name: 'Agachamento Profundo com Cabeça ao Chão', description: 'Alongamento em agachamento profundo levando a cabeça ao chão para soltar quadril, posteriores e lombar.',
        instructions: ['Fique em pé com os pés além da largura do quadril', 'Agache e apoie as mãos no chão', 'Leve a cabeça em direção ao chão', 'Respire fundo e mantenha a posição'],
        commonMistakes: ['Forçar o pescoço', 'Levantar os calcanhares', 'Fazer movimentos de balanço'],
        musclesWorked: ['Posteriores de Coxa', 'Glúteos', 'Adutores', 'Eretores da Espinha'] },
      es: { name: 'Sentadilla Profunda con Cabeza al Suelo', description: 'Estiramiento en sentadilla profunda llevando la cabeza al suelo.',
        instructions: ['De pie con pies más anchos que la cadera', 'Agáchate y apoya las manos en el suelo', 'Baja la cabeza hacia el suelo', 'Respira hondo y mantén'],
        commonMistakes: ['Forzar el cuello', 'Levantar los talones', 'Rebotar en el estiramiento'],
        musclesWorked: ['Isquiotibiales', 'Glúteos', 'Aductores', 'Erectores Espinales'] },
    },
  },
  {
    id: 'squat-mobility-side-bend',
    name: 'Squat Mobility Side Bend',
    muscleGroup: 'Full Body',
    equipment: 'None',
    level: 'beginner',
    type: 'calisthenics',
    category: 'stretching',
    videoUrl: squatMobilitySideBend.url,
    description: 'Deep-squat mobility drill with a controlled side bend to open the hips, torso and shoulders.',
    instructions: ['Stand with the feet wider than the hips', 'Lower into a comfortable deep squat', 'Reach one arm overhead and bend the torso gently to the opposite side', 'Return to the center and alternate sides with control'],
    commonMistakes: ['Letting the heels lift', 'Collapsing the chest forward', 'Forcing the side bend', 'Moving too quickly'],
    musclesWorked: ['Glutes', 'Adductors', 'Obliques', 'Shoulders'],
    sets: 2, reps: '8-10 cada lado', restSeconds: 30,
    translations: {
      pt: { name: 'Mobilidade no Agachamento com Inclinação Lateral', description: 'Mobilidade em agachamento profundo com inclinação lateral controlada para abrir quadril, tronco e ombros.',
        instructions: ['Fique em pé com os pés além da largura do quadril', 'Desça até um agachamento profundo confortável', 'Leve um braço acima da cabeça e incline o tronco suavemente para o lado oposto', 'Volte ao centro e alterne os lados com controle'],
        commonMistakes: ['Levantar os calcanhares', 'Deixar o peito cair para frente', 'Forçar a inclinação lateral', 'Executar rápido demais'],
        musclesWorked: ['Glúteos', 'Adutores', 'Oblíquos', 'Ombros'] },
      es: { name: 'Movilidad en Sentadilla con Inclinación Lateral', description: 'Movilidad en sentadilla profunda con inclinación lateral controlada para abrir caderas, torso y hombros.',
        instructions: ['Ponte de pie con los pies más anchos que la cadera', 'Baja a una sentadilla profunda cómoda', 'Lleva un brazo sobre la cabeza e inclina suavemente el torso al lado contrario', 'Vuelve al centro y alterna los lados con control'],
        commonMistakes: ['Levantar los talones', 'Dejar caer el pecho hacia delante', 'Forzar la inclinación lateral', 'Moverse demasiado rápido'],
        musclesWorked: ['Glúteos', 'Aductores', 'Oblicuos', 'Hombros'] },
    },
  },
];
